// ---------------------------------------------------------------------------
// Auto-generated from lldate_test.cpp at 2025-10-16T20:37:40+00:00
// Generated by gen_tut_to_doctest.py
// ---------------------------------------------------------------------------
#include "doctest.h"
#include "indra/test/ll_doctest_helpers.h"
#include "indra/test/tut_compat_doctest.h"
#include "linden_common.h"
#include "../llstring.h"
#include "../lldate.h"

/**
 * @file lldate_test.cpp
 * @author Adroit
 * @date 2007-02
 * @brief LLDate test cases.
 *
 * $LicenseInfo:firstyear=2007&license=viewerlgpl$
 * Second Life Viewer Source Code
 * Copyright (C) 2010, Linden Research, Inc.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation;
 * version 2.1 of the License only.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 * Linden Research, Inc., 945 Battery Street, San Francisco, CA  94111  USA
 * $/LicenseInfo$
 */





#define VALID_DATE                                  "2003-04-30T04:00:00Z"
#define VALID_DATE_LEAP                             "2004-02-29T04:00:00Z"
#define VALID_DATE_HOUR_BOUNDARY                    "2003-04-30T23:59:59Z"
#define VALID_DATE_FRACTIONAL_SECS                  "2007-09-26T20:31:33.70Z"

// invalid format
#define INVALID_DATE_MISSING_YEAR                   "-04-30T22:59:59Z"
#define INVALID_DATE_MISSING_MONTH                  "1900-0430T22:59:59Z"
#define INVALID_DATE_MISSING_DATE                   "1900-0430-T22:59:59Z"
#define INVALID_DATE_MISSING_T                      "1900-04-30-22:59:59Z"
#define INVALID_DATE_MISSING_HOUR                   "1900-04-30T:59:59Z"
#define INVALID_DATE_MISSING_MIN                    "1900-04-30T01::59Z"
#define INVALID_DATE_MISSING_SEC                    "1900-04-30T01:59Z"
#define INVALID_DATE_MISSING_Z                      "1900-04-30T01:59:23"
#define INVALID_DATE_EMPTY                          ""

// invalid values
// apr 1.1.1 seems to not care about constraining the date to valid
// dates. Put these back when the parser checks.
#define LL_DATE_PARSER_CHECKS_BOUNDARY 0
//#define INVALID_DATE_24HOUR_BOUNDARY              "2003-04-30T24:00:00Z"
//#define INVALID_DATE_LEAP                         "2003-04-29T04:00:00Z"
//#define INVALID_DATE_HOUR                         "2003-04-30T24:59:59Z"
//#define INVALID_DATE_MIN                          "2003-04-30T22:69:59Z"
//#define INVALID_DATE_SEC                          "2003-04-30T22:59:69Z"
//#define INVALID_DATE_YEAR                         "0-04-30T22:59:59Z"
//#define INVALID_DATE_MONTH                            "2003-13-30T22:59:59Z"
//#define INVALID_DATE_DAY                          "2003-04-35T22:59:59Z"

namespace tut
{
    using tut_compat::ensure;
    using tut_compat::ensure_equals;
    using tut_compat::ensure_not;
    using tut_compat::ensure_throws;

        struct date_test
        {

        };

        /* format validation */


        /* Invalid Value Handling */


        /* API checks */
} // namespace tut

TUT_SUITE("lldate_test")
{
    TUT_CASE("lldate_test::date_test_object_t_test_1")
    {
        using namespace tut;
        LLDate date(VALID_DATE);
        std::string  expected_string;
        bool result;
        expected_string = VALID_DATE;
        TUT_ENSURE_EQ("Valid Date failed", expected_string, date.asString());

        result = date.fromString(VALID_DATE_LEAP);
        expected_string = VALID_DATE_LEAP;
        TUT_ENSURE_EQ("VALID_DATE_LEAP failed", expected_string, date.asString());

        result = date.fromString(VALID_DATE_HOUR_BOUNDARY);
        expected_string = VALID_DATE_HOUR_BOUNDARY;
        TUT_ENSURE_EQ("VALID_DATE_HOUR_BOUNDARY failed", expected_string, date.asString());

        result = date.fromString(VALID_DATE_FRACTIONAL_SECS);
        expected_string = VALID_DATE_FRACTIONAL_SECS;
        TUT_ENSURE_EQ("VALID_DATE_FRACTIONAL_SECS failed", expected_string, date.asString());

        result = date.fromString(INVALID_DATE_MISSING_YEAR);
        TUT_ENSURE_EQ("INVALID_DATE_MISSING_YEAR should have failed", result, false);

        result = date.fromString(INVALID_DATE_MISSING_MONTH);
        TUT_ENSURE_EQ("INVALID_DATE_MISSING_MONTH should have failed", result, false);

        result = date.fromString(INVALID_DATE_MISSING_DATE);
        TUT_ENSURE_EQ("INVALID_DATE_MISSING_DATE should have failed", result, false);

        result = date.fromString(INVALID_DATE_MISSING_T);
        TUT_ENSURE_EQ("INVALID_DATE_MISSING_T should have failed", result, false);

        result = date.fromString(INVALID_DATE_MISSING_HOUR);
        TUT_ENSURE_EQ("INVALID_DATE_MISSING_HOUR should have failed", result, false);

        result = date.fromString(INVALID_DATE_MISSING_MIN);
        TUT_ENSURE_EQ("INVALID_DATE_MISSING_MIN should have failed", result, false);

        result = date.fromString(INVALID_DATE_MISSING_SEC);
        TUT_ENSURE_EQ("INVALID_DATE_MISSING_SEC should have failed", result, false);

        result = date.fromString(INVALID_DATE_MISSING_Z);
        TUT_ENSURE_EQ("INVALID_DATE_MISSING_Z should have failed", result, false);

        result = date.fromString(INVALID_DATE_EMPTY);
        TUT_ENSURE_EQ("INVALID_DATE_EMPTY should have failed", result, false);
    }

    TUT_CASE("lldate_test::date_test_object_t_test_2")
    {
        using namespace tut;
        #if LL_DATE_PARSER_CHECKS_BOUNDARY
                LLDate date;
                std::string  expected_string;
                bool result;

                result = date.fromString(INVALID_DATE_24HOUR_BOUNDARY);
                TUT_ENSURE_EQ("INVALID_DATE_24HOUR_BOUNDARY should have failed", result, false);
                TUT_ENSURE_EQ("INVALID_DATE_24HOUR_BOUNDARY date still set to old value on failure!", date.secondsSinceEpoch(), 0);

                result = date.fromString(INVALID_DATE_LEAP);
                TUT_ENSURE_EQ("INVALID_DATE_LEAP should have failed", result, false);

                result = date.fromString(INVALID_DATE_HOUR);
                TUT_ENSURE_EQ("INVALID_DATE_HOUR should have failed", result, false);

                result = date.fromString(INVALID_DATE_MIN);
                TUT_ENSURE_EQ("INVALID_DATE_MIN should have failed", result, false);

                result = date.fromString(INVALID_DATE_SEC);
                TUT_ENSURE_EQ("INVALID_DATE_SEC should have failed", result, false);

                result = date.fromString(INVALID_DATE_YEAR);
                TUT_ENSURE_EQ("INVALID_DATE_YEAR should have failed", result, false);

                result = date.fromString(INVALID_DATE_MONTH);
                TUT_ENSURE_EQ("INVALID_DATE_MONTH should have failed", result, false);

                result = date.fromString(INVALID_DATE_DAY);
                TUT_ENSURE_EQ("INVALID_DATE_DAY should have failed", result, false);
        #endif
    }

    TUT_CASE("lldate_test::date_test_object_t_test_3")
    {
        using namespace tut;
        LLDate date;
        std::istringstream stream(VALID_DATE);
        std::string  expected_string = VALID_DATE;
        date.fromStream(stream);
        TUT_ENSURE_EQ("fromStream failed", date.asString(), expected_string);
    }

    TUT_CASE("lldate_test::date_test_object_t_test_4")
    {
        using namespace tut;
        LLDate date1(VALID_DATE);
        LLDate date2(date1);
        TUT_ENSURE_EQ("LLDate(const LLDate& date) constructor failed", date1.asString(), date2.asString());
    }

    TUT_CASE("lldate_test::date_test_object_t_test_5")
    {
        using namespace tut;
        LLDate date1(VALID_DATE);
        LLDate date2(date1.secondsSinceEpoch());
        TUT_ENSURE_EQ("secondsSinceEpoch not equal", date1.secondsSinceEpoch(), date2.secondsSinceEpoch());
        TUT_ENSURE_EQ("LLDate created using secondsSinceEpoch not equal", date1.asString(), date2.asString());
    }

    TUT_CASE("lldate_test::date_test_object_t_test_6")
    {
        using namespace tut;
        LLDate date(VALID_DATE);
        std::ostringstream stream;
        stream << date;
        std::string expected_str = VALID_DATE;
        TUT_ENSURE_EQ("ostringstream failed", expected_str, stream.str());
    }

    TUT_CASE("lldate_test::date_test_object_t_test_7")
    {
        using namespace tut;
        LLDate date;
        std::istringstream stream(VALID_DATE);
        stream >> date;
        std::string expected_str = VALID_DATE;
        std::ostringstream out_stream;
        out_stream << date;

        TUT_ENSURE_EQ("<< failed", date.asString(), expected_str);
        TUT_ENSURE_EQ("<< to >> failed", stream.str(), out_stream.str());
    }
}
