// ---------------------------------------------------------------------------
// Auto-generated from lldeadmantimer_test.cpp at 2025-10-16T20:37:40+00:00
// Generated by gen_tut_to_doctest.py
// ---------------------------------------------------------------------------
#include "doctest.h"
#include "indra/test/ll_doctest_helpers.h"
#include "indra/test/tut_compat_doctest.h"
#include "linden_common.h"
#include "../lldeadmantimer.h"
#include "../llsd.h"
#include "../lltimer.h"

/**
 * @file lldeadmantimer_test.cpp
 * @brief Tests for the LLDeadmanTimer class.
 *
 * $LicenseInfo:firstyear=2013&license=viewerlgpl$
 * Second Life Viewer Source Code
 * Copyright (C) 2013, Linden Research, Inc.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation;
 * version 2.1 of the License only.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 * Linden Research, Inc., 945 Battery Street, San Francisco, CA  94111  USA
 * $/LicenseInfo$
 */




// Convert between floating point time deltas and U64 time deltas.
// Reflects an implementation detail inside lldeadmantimer.cpp

static LLDeadmanTimer::time_type float_time_to_u64(F64 delta)
{
    return LLDeadmanTimer::time_type(delta * get_timer_info().mClockFrequency);
}

static F64 u64_time_to_float(LLDeadmanTimer::time_type delta)
{
    return delta * get_timer_info().mClockFrequencyInv;
}


namespace tut
{
    using tut_compat::ensure;
    using tut_compat::ensure_equals;
    using tut_compat::ensure_not;
    using tut_compat::ensure_throws;

    struct deadmantimer_test
    {
        deadmantimer_test()
            {
                // LLTimer internals updating
                get_timer_info().update();
            }
    };


    // Basic construction test and isExpired() call



    // Construct with zero horizon - not useful generally but will be useful in testing



    // "pre-expired" timer - starting a timer with a 0.0 horizon will result in
    // expiration on first test.



    // "pre-expired" timer - bell rings are ignored as we're already expired.



    // start(0) test - unexpired timer reports unexpired



    // start() test - start in the past but not beyond 1 horizon



    // start() test - start in the past but well beyond 1 horizon



    // isExpired() test - results are read-once.  Probes after first true are false.



    // ringBell() test - see that we can keep a timer from expiring



    // restart after expiration test - verify that restarts behave well
} // namespace tut // end namespace tut

TUT_SUITE("lldeadmantimer_test")
{
    TUT_CASE("lldeadmantimer_test::deadmantimer_object_t_test_1")
    {
        using namespace tut;
        {
            // Without cpu metrics
            F64 started(42.0), stopped(97.0);
            U64 count(U64L(8));
            LLDeadmanTimer timer(10.0, false);

            TUT_ENSURE_EQ("WOCM isExpired() returns false after ctor()", timer.isExpired(0, started, stopped, count), false);
            TUT_CHECK_MSG((started) == doctest::Approx(F64(42.0)).epsilon(2), "WOCM t1 - isExpired() does not modify started");
            TUT_CHECK_MSG((stopped) == doctest::Approx(F64(97.0)).epsilon(2), "WOCM t1 - isExpired() does not modify stopped");
            TUT_ENSURE_EQ("WOCM t1 - isExpired() does not modify count", count, U64L(8));
        }

        {
            // With cpu metrics
            F64 started(42.0), stopped(97.0);
            U64 count(U64L(8)), user_cpu(29000), sys_cpu(57000);
            LLDeadmanTimer timer(10.0, true);

            TUT_ENSURE_EQ("WCM isExpired() returns false after ctor()", timer.isExpired(0, started, stopped, count, user_cpu, sys_cpu), false);
            TUT_CHECK_MSG((started) == doctest::Approx(F64(42.0)).epsilon(2), "WCM t1 - isExpired() does not modify started");
            TUT_CHECK_MSG((stopped) == doctest::Approx(F64(97.0)).epsilon(2), "WCM t1 - isExpired() does not modify stopped");
            TUT_ENSURE_EQ("WCM t1 - isExpired() does not modify count", count, U64L(8));
            TUT_ENSURE_EQ("WCM t1 - isExpired() does not modify user_cpu", user_cpu, U64L(29000));
            TUT_ENSURE_EQ("WCM t1 - isExpired() does not modify sys_cpu", sys_cpu, U64L(57000));
        }
    }

    TUT_CASE("lldeadmantimer_test::deadmantimer_object_t_test_2")
    {
        using namespace tut;
        {
            // Without cpu metrics
            F64 started(42.0), stopped(97.0);
            U64 count(U64L(8));
            LLDeadmanTimer timer(0.0, false);           // Zero is pre-expired

            TUT_ENSURE_EQ("WOCM isExpired() still returns false with 0.0 time ctor()", timer.isExpired(0, started, stopped, count), false);
        }

        {
            // With cpu metrics
            F64 started(42.0), stopped(97.0);
            U64 count(U64L(8)), user_cpu(29000), sys_cpu(57000);
            LLDeadmanTimer timer(0.0, true);            // Zero is pre-expired

            TUT_ENSURE_EQ("WCM isExpired() still returns false with 0.0 time ctor()", timer.isExpired(0, started, stopped, count, user_cpu, sys_cpu), false);
        }
    }

    TUT_CASE("lldeadmantimer_test::deadmantimer_object_t_test_3")
    {
        using namespace tut;
        {
            // Without cpu metrics
            F64 started(42.0), stopped(97.0);
            U64 count(U64L(8));
            LLDeadmanTimer timer(0.0, false);

            timer.start(0);
            TUT_ENSURE_EQ("WOCM isExpired() returns true with 0.0 horizon time", timer.isExpired(0, started, stopped, count), true);
            TUT_CHECK_MSG((started) == doctest::Approx(stopped).epsilon(8), "WOCM expired timer with no bell ringing has stopped == started");
        }
        {
            // With cpu metrics
            F64 started(42.0), stopped(97.0);
            U64 count(U64L(8)), user_cpu(29000), sys_cpu(57000);
            LLDeadmanTimer timer(0.0, true);

            timer.start(0);
            TUT_ENSURE_EQ("WCM isExpired() returns true with 0.0 horizon time", timer.isExpired(0, started, stopped, count, user_cpu, sys_cpu), true);
            TUT_CHECK_MSG((started) == doctest::Approx(stopped).epsilon(8), "WCM expired timer with no bell ringing has stopped == started");
        }
    }

    TUT_CASE("lldeadmantimer_test::deadmantimer_object_t_test_4")
    {
        using namespace tut;
        {
            // Without cpu metrics
            F64 started(42.0), stopped(97.0);
            U64 count(U64L(8));
            LLDeadmanTimer timer(0.0, false);

            timer.start(0);
            timer.ringBell(LLDeadmanTimer::getNow() + float_time_to_u64(1000.0), 1);
            TUT_ENSURE_EQ("WOCM isExpired() returns true with 0.0 horizon time after bell ring", timer.isExpired(0, started, stopped, count), true);
            TUT_CHECK_MSG((started) == doctest::Approx(stopped).epsilon(8), "WOCM ringBell has no impact on expired timer leaving stopped == started");
        }
        {
            // With cpu metrics
            F64 started(42.0), stopped(97.0);
            U64 count(U64L(8)), user_cpu(29000), sys_cpu(57000);
            LLDeadmanTimer timer(0.0, true);

            timer.start(0);
            timer.ringBell(LLDeadmanTimer::getNow() + float_time_to_u64(1000.0), 1);
            TUT_ENSURE_EQ("WCM isExpired() returns true with 0.0 horizon time after bell ring", timer.isExpired(0, started, stopped, count, user_cpu, sys_cpu), true);
            TUT_CHECK_MSG((started) == doctest::Approx(stopped).epsilon(8), "WCM ringBell has no impact on expired timer leaving stopped == started");
        }
    }

    TUT_CASE("lldeadmantimer_test::deadmantimer_object_t_test_5")
    {
        using namespace tut;
        {
            // Without cpu metrics
            F64 started(42.0), stopped(97.0);
            U64 count(U64L(8));
            LLDeadmanTimer timer(10.0, false);

            timer.start(0);
            TUT_ENSURE_EQ("WOCM isExpired() returns false after starting with 10.0 horizon time", timer.isExpired(0, started, stopped, count), false);
            TUT_CHECK_MSG((started) == doctest::Approx(F64(42.0)).epsilon(2), "WOCM t5 - isExpired() does not modify started");
            TUT_CHECK_MSG((stopped) == doctest::Approx(F64(97.0)).epsilon(2), "WOCM t5 - isExpired() does not modify stopped");
            TUT_ENSURE_EQ("WOCM t5 - isExpired() does not modify count", count, U64L(8));
        }
        {
            // With cpu metrics
            F64 started(42.0), stopped(97.0);
            U64 count(U64L(8)), user_cpu(29000), sys_cpu(57000);
            LLDeadmanTimer timer(10.0, true);

            timer.start(0);
            TUT_ENSURE_EQ("WCM isExpired() returns false after starting with 10.0 horizon time", timer.isExpired(0, started, stopped, count, user_cpu, sys_cpu), false);
            TUT_CHECK_MSG((started) == doctest::Approx(F64(42.0)).epsilon(2), "WCM t5 - isExpired() does not modify started");
            TUT_CHECK_MSG((stopped) == doctest::Approx(F64(97.0)).epsilon(2), "WCM t5 - isExpired() does not modify stopped");
            TUT_ENSURE_EQ("WCM t5 - isExpired() does not modify count", count, U64L(8));
            TUT_ENSURE_EQ("WCM t5 - isExpired() does not modify user_cpu", user_cpu, U64L(29000));
            TUT_ENSURE_EQ("WCM t5 - isExpired() does not modify sys_cpu", sys_cpu, U64L(57000));
        }
    }

    TUT_CASE("lldeadmantimer_test::deadmantimer_object_t_test_6")
    {
        using namespace tut;
        {
            // Without cpu metrics
            F64 started(42.0), stopped(97.0);
            U64 count(U64L(8));
            LLDeadmanTimer timer(10.0, false);

            // Would like to do subtraction on current time but can't because
            // the implementation on Windows is zero-based.  We wrap around
            // the backside resulting in a large U64 number.

            LLDeadmanTimer::time_type the_past(LLDeadmanTimer::getNow());
            LLDeadmanTimer::time_type now(the_past + float_time_to_u64(5.0));
            timer.start(the_past);
            TUT_ENSURE_EQ("WOCM t6 - isExpired() returns false with 10.0 horizon time starting 5.0 in past", timer.isExpired(now, started, stopped, count), false);
            TUT_CHECK_MSG((started) == doctest::Approx(F64(42.0)).epsilon(2), "WOCM t6 - isExpired() does not modify started");
            TUT_CHECK_MSG((stopped) == doctest::Approx(F64(97.0)).epsilon(2), "WOCM t6 - isExpired() does not modify stopped");
            TUT_ENSURE_EQ("WOCM t6 - isExpired() does not modify count", count, U64L(8));
        }
        {
            // With cpu metrics
            F64 started(42.0), stopped(97.0);
            U64 count(U64L(8)), user_cpu(29000), sys_cpu(57000);
            LLDeadmanTimer timer(10.0, true);

            // Would like to do subtraction on current time but can't because
            // the implementation on Windows is zero-based.  We wrap around
            // the backside resulting in a large U64 number.

            LLDeadmanTimer::time_type the_past(LLDeadmanTimer::getNow());
            LLDeadmanTimer::time_type now(the_past + float_time_to_u64(5.0));
            timer.start(the_past);
            TUT_ENSURE_EQ("WCM t6 - isExpired() returns false with 10.0 horizon time starting 5.0 in past", timer.isExpired(now, started, stopped, count, user_cpu, sys_cpu), false);
            TUT_CHECK_MSG((started) == doctest::Approx(F64(42.0)).epsilon(2), "WCM t6 - isExpired() does not modify started");
            TUT_CHECK_MSG((stopped) == doctest::Approx(F64(97.0)).epsilon(2), "WCM t6 - isExpired() does not modify stopped");
            TUT_ENSURE_EQ("t6 - isExpired() does not modify count", count, U64L(8));
            TUT_ENSURE_EQ("WCM t6 - isExpired() does not modify user_cpu", user_cpu, U64L(29000));
            TUT_ENSURE_EQ("WCM t6 - isExpired() does not modify sys_cpu", sys_cpu, U64L(57000));
        }
    }

    TUT_CASE("lldeadmantimer_test::deadmantimer_object_t_test_7")
    {
        using namespace tut;
        {
            // Without cpu metrics
            F64 started(42.0), stopped(97.0);
            U64 count(U64L(8));
            LLDeadmanTimer timer(10.0, false);

            // Would like to do subtraction on current time but can't because
            // the implementation on Windows is zero-based.  We wrap around
            // the backside resulting in a large U64 number.

            LLDeadmanTimer::time_type the_past(LLDeadmanTimer::getNow());
            LLDeadmanTimer::time_type now(the_past + float_time_to_u64(20.0));
            timer.start(the_past);
            TUT_ENSURE_EQ("WOCM t7 - isExpired() returns true with 10.0 horizon time starting 20.0 in past", timer.isExpired(now,started, stopped, count), true);
            TUT_CHECK_MSG((started) == doctest::Approx(stopped).epsilon(8), "WOCM t7 - starting before horizon still gives equal started / stopped");
        }
        {
            // With cpu metrics
            F64 started(42.0), stopped(97.0);
            U64 count(U64L(8)), user_cpu(29000), sys_cpu(57000);
            LLDeadmanTimer timer(10.0, true);

            // Would like to do subtraction on current time but can't because
            // the implementation on Windows is zero-based.  We wrap around
            // the backside resulting in a large U64 number.

            LLDeadmanTimer::time_type the_past(LLDeadmanTimer::getNow());
            LLDeadmanTimer::time_type now(the_past + float_time_to_u64(20.0));
            timer.start(the_past);
            TUT_ENSURE_EQ("WCM t7 - isExpired() returns true with 10.0 horizon time starting 20.0 in past", timer.isExpired(now,started, stopped, count, user_cpu, sys_cpu), true);
            TUT_CHECK_MSG((started) == doctest::Approx(stopped).epsilon(8), "WOCM t7 - starting before horizon still gives equal started / stopped");
        }
    }

    TUT_CASE("lldeadmantimer_test::deadmantimer_object_t_test_8")
    {
        using namespace tut;
        {
            // Without cpu metrics
            F64 started(42.0), stopped(97.0);
            U64 count(U64L(8));
            LLDeadmanTimer timer(10.0, false);

            // Would like to do subtraction on current time but can't because
            // the implementation on Windows is zero-based.  We wrap around
            // the backside resulting in a large U64 number.

            LLDeadmanTimer::time_type the_past(LLDeadmanTimer::getNow());
            LLDeadmanTimer::time_type now(the_past + float_time_to_u64(20.0));
            timer.start(the_past);
            TUT_ENSURE_EQ("WOCM t8 - isExpired() returns true with 10.0 horizon time starting 20.0 in past", timer.isExpired(now, started, stopped, count), true);

            started = 42.0;
            stopped = 97.0;
            count = U64L(8);
            TUT_ENSURE_EQ("WOCM t8 - second isExpired() returns false after true", timer.isExpired(now, started, stopped, count), false);
            TUT_CHECK_MSG((started) == doctest::Approx(F64(42.0)).epsilon(2), "WOCM t8 - 2nd isExpired() does not modify started");
            TUT_CHECK_MSG((stopped) == doctest::Approx(F64(97.0)).epsilon(2), "WOCM t8 - 2nd isExpired() does not modify stopped");
            TUT_ENSURE_EQ("WOCM t8 - 2nd isExpired() does not modify count", count, U64L(8));
        }
        {
            // With cpu metrics
            F64 started(42.0), stopped(97.0);
            U64 count(U64L(8)), user_cpu(29000), sys_cpu(57000);
            LLDeadmanTimer timer(10.0, true);

            // Would like to do subtraction on current time but can't because
            // the implementation on Windows is zero-based.  We wrap around
            // the backside resulting in a large U64 number.

            LLDeadmanTimer::time_type the_past(LLDeadmanTimer::getNow());
            LLDeadmanTimer::time_type now(the_past + float_time_to_u64(20.0));
            timer.start(the_past);
            TUT_ENSURE_EQ("WCM t8 - isExpired() returns true with 10.0 horizon time starting 20.0 in past", timer.isExpired(now, started, stopped, count, user_cpu, sys_cpu), true);

            started = 42.0;
            stopped = 97.0;
            count = U64L(8);
            user_cpu = 29000;
            sys_cpu = 57000;
            TUT_ENSURE_EQ("WCM t8 - second isExpired() returns false after true", timer.isExpired(now, started, stopped, count), false);
            TUT_CHECK_MSG((started) == doctest::Approx(F64(42.0)).epsilon(2), "WCM t8 - 2nd isExpired() does not modify started");
            TUT_CHECK_MSG((stopped) == doctest::Approx(F64(97.0)).epsilon(2), "WCM t8 - 2nd isExpired() does not modify stopped");
            TUT_ENSURE_EQ("WCM t8 - 2nd isExpired() does not modify count", count, U64L(8));
            TUT_ENSURE_EQ("WCM t8 - 2nd isExpired() does not modify user_cpu", user_cpu, U64L(29000));
            TUT_ENSURE_EQ("WCM t8 - 2nd isExpired() does not modify sys_cpu", sys_cpu, U64L(57000));
        }
    }

    TUT_CASE("lldeadmantimer_test::deadmantimer_object_t_test_9")
    {
        using namespace tut;
        {
            // Without cpu metrics
            F64 started(42.0), stopped(97.0);
            U64 count(U64L(8));
            LLDeadmanTimer timer(5.0, false);

            LLDeadmanTimer::time_type now(LLDeadmanTimer::getNow());
            F64 real_start(u64_time_to_float(now));
            timer.start(0);

            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            TUT_ENSURE_EQ("WOCM t9 - 5.0 horizon timer has not timed out after 10 1-second bell rings", timer.isExpired(now, started, stopped, count), false);
            F64 last_good_ring(u64_time_to_float(now));

            // Jump forward and expire
            now += float_time_to_u64(10.0);
            TUT_ENSURE_EQ("WOCM t9 - 5.0 horizon timer expires on 10-second jump", timer.isExpired(now, started, stopped, count), true);
            TUT_CHECK_MSG((started) == doctest::Approx(real_start).epsilon(4), "WOCM t9 - started matches start() time");
            TUT_CHECK_MSG((stopped) == doctest::Approx(last_good_ring).epsilon(4), "WOCM t9 - stopped matches last ringBell() time");
            TUT_ENSURE_EQ("WOCM t9 - 10 good ringBell()s", count, U64L(10));
            TUT_ENSURE_EQ("WOCM t9 - single read only", timer.isExpired(now, started, stopped, count), false);
        }
        {
            // With cpu metrics
            F64 started(42.0), stopped(97.0);
            U64 count(U64L(8)), user_cpu(29000), sys_cpu(57000);
            LLDeadmanTimer timer(5.0, true);

            LLDeadmanTimer::time_type now(LLDeadmanTimer::getNow());
            F64 real_start(u64_time_to_float(now));
            timer.start(0);

            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            TUT_ENSURE_EQ("WCM t9 - 5.0 horizon timer has not timed out after 10 1-second bell rings", timer.isExpired(now, started, stopped, count, user_cpu, sys_cpu), false);
            F64 last_good_ring(u64_time_to_float(now));

            // Jump forward and expire
            now += float_time_to_u64(10.0);
            TUT_ENSURE_EQ("WCM t9 - 5.0 horizon timer expires on 10-second jump", timer.isExpired(now, started, stopped, count, user_cpu, sys_cpu), true);
            TUT_CHECK_MSG((started) == doctest::Approx(real_start).epsilon(4), "WCM t9 - started matches start() time");
            TUT_CHECK_MSG((stopped) == doctest::Approx(last_good_ring).epsilon(4), "WCM t9 - stopped matches last ringBell() time");
            TUT_ENSURE_EQ("WCM t9 - 10 good ringBell()s", count, U64L(10));
            TUT_ENSURE_EQ("WCM t9 - single read only", timer.isExpired(now, started, stopped, count, user_cpu, sys_cpu), false);
        }
    }

    TUT_CASE("lldeadmantimer_test::deadmantimer_object_t_test_10")
    {
        using namespace tut;
        {
            // Without cpu metrics
            F64 started(42.0), stopped(97.0);
            U64 count(U64L(8));
            LLDeadmanTimer timer(5.0, false);

            LLDeadmanTimer::time_type now(LLDeadmanTimer::getNow());
            F64 real_start(u64_time_to_float(now));
            timer.start(0);

            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            TUT_ENSURE_EQ("WOCM t10 - 5.0 horizon timer has not timed out after 10 1-second bell rings", timer.isExpired(now, started, stopped, count), false);
            F64 last_good_ring(u64_time_to_float(now));

            // Jump forward and expire
            now += float_time_to_u64(10.0);
            TUT_ENSURE_EQ("WOCM t10 - 5.0 horizon timer expires on 10-second jump", timer.isExpired(now, started, stopped, count), true);
            TUT_CHECK_MSG((started) == doctest::Approx(real_start).epsilon(4), "WOCM t10 - started matches start() time");
            TUT_CHECK_MSG((stopped) == doctest::Approx(last_good_ring).epsilon(4), "WOCM t10 - stopped matches last ringBell() time");
            TUT_ENSURE_EQ("WOCM t10 - 10 good ringBell()s", count, U64L(10));
            TUT_ENSURE_EQ("WOCM t10 - single read only", timer.isExpired(now, started, stopped, count), false);

            // Jump forward and restart
            now += float_time_to_u64(1.0);
            real_start = u64_time_to_float(now);
            timer.start(now);

            // Run a modified bell ring sequence
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            TUT_ENSURE_EQ("WOCM t10 - 5.0 horizon timer has not timed out after 8 1-second bell rings", timer.isExpired(now, started, stopped, count), false);
            last_good_ring = u64_time_to_float(now);

            // Jump forward and expire
            now += float_time_to_u64(10.0);
            TUT_ENSURE_EQ("WOCM t10 - 5.0 horizon timer expires on 8-second jump", timer.isExpired(now, started, stopped, count), true);
            TUT_CHECK_MSG((started) == doctest::Approx(real_start).epsilon(4), "WOCM t10 - 2nd started matches start() time");
            TUT_CHECK_MSG((stopped) == doctest::Approx(last_good_ring).epsilon(4), "WOCM t10 - 2nd stopped matches last ringBell() time");
            TUT_ENSURE_EQ("WOCM t10 - 8 good ringBell()s", count, U64L(8));
            TUT_ENSURE_EQ("WOCM t10 - single read only - 2nd start", timer.isExpired(now, started, stopped, count), false);
        }
        {
            // With cpu metrics
            F64 started(42.0), stopped(97.0);
            U64 count(U64L(8)), user_cpu(29000), sys_cpu(57000);

            LLDeadmanTimer timer(5.0, true);

            LLDeadmanTimer::time_type now(LLDeadmanTimer::getNow());
            F64 real_start(u64_time_to_float(now));
            timer.start(0);

            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            TUT_ENSURE_EQ("WCM t10 - 5.0 horizon timer has not timed out after 10 1-second bell rings", timer.isExpired(now, started, stopped, count, user_cpu, sys_cpu), false);
            F64 last_good_ring(u64_time_to_float(now));

            // Jump forward and expire
            now += float_time_to_u64(10.0);
            TUT_ENSURE_EQ("WCM t10 - 5.0 horizon timer expires on 10-second jump", timer.isExpired(now, started, stopped, count, user_cpu, sys_cpu), true);
            TUT_CHECK_MSG((started) == doctest::Approx(real_start).epsilon(4), "WCM t10 - started matches start() time");
            TUT_CHECK_MSG((stopped) == doctest::Approx(last_good_ring).epsilon(4), "WCM t10 - stopped matches last ringBell() time");
            TUT_ENSURE_EQ("WCM t10 - 10 good ringBell()s", count, U64L(10));
            TUT_ENSURE_EQ("WCM t10 - single read only", timer.isExpired(now, started, stopped, count, user_cpu, sys_cpu), false);

            // Jump forward and restart
            now += float_time_to_u64(1.0);
            real_start = u64_time_to_float(now);
            timer.start(now);

            // Run a modified bell ring sequence
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            now += float_time_to_u64(1.0);
            timer.ringBell(now, 1);
            TUT_ENSURE_EQ("WCM t10 - 5.0 horizon timer has not timed out after 8 1-second bell rings", timer.isExpired(now, started, stopped, count, user_cpu, sys_cpu), false);
            last_good_ring = u64_time_to_float(now);

            // Jump forward and expire
            now += float_time_to_u64(10.0);
            TUT_ENSURE_EQ("WCM t10 - 5.0 horizon timer expires on 8-second jump", timer.isExpired(now, started, stopped, count, user_cpu, sys_cpu), true);
            TUT_CHECK_MSG((started) == doctest::Approx(real_start).epsilon(4), "WCM t10 - 2nd started matches start() time");
            TUT_CHECK_MSG((stopped) == doctest::Approx(last_good_ring).epsilon(4), "WCM t10 - 2nd stopped matches last ringBell() time");
            TUT_ENSURE_EQ("WCM t10 - 8 good ringBell()s", count, U64L(8));
            TUT_ENSURE_EQ("WCM t10 - single read only - 2nd start", timer.isExpired(now, started, stopped, count, user_cpu, sys_cpu), false);
        }
    }
}
