// ---------------------------------------------------------------------------
// Auto-generated from llheteromap_test.cpp at 2025-10-16T20:37:40+00:00
// Generated by gen_tut_to_doctest.py
// ---------------------------------------------------------------------------
#include "doctest.h"
#include "indra/test/ll_doctest_helpers.h"
#include "indra/test/tut_compat_doctest.h"
#include "linden_common.h"
#include "llheteromap.h"
#include <set>

/**
 * @file   llheteromap_test.cpp
 * @author Nat Goodspeed
 * @date   2016-10-12
 * @brief  Test for llheteromap.
 *
 * $LicenseInfo:firstyear=2016&license=viewerlgpl$
 * Copyright (c) 2016, Linden Research, Inc.
 * $/LicenseInfo$
 */

// Precompiled header
// associated header
// STL headers
// std headers
// external library headers

// (pacify clang)
std::ostream& operator<<(std::ostream& out, const std::set<std::string>& strset);
// other Linden headers

static std::string clog;
static std::set<std::string> dlog;

// want to be able to use ensure_equals() on a set<string>
std::ostream& operator<<(std::ostream& out, const std::set<std::string>& strset)
{
    out << '{';
    const char* delim = "";
    for (std::set<std::string>::const_iterator si(strset.begin()), se(strset.end());
         si != se; ++si)
    {
        out << delim << '"' << *si << '"';
        delim = ", ";
    }
    out << '}';
    return out;
}

// unrelated test classes
struct Chalk
{
    int dummy;
    std::string name;

    Chalk():
        dummy(0)
    {
        clog.append("a");
    }

    ~Chalk()
    {
        dlog.insert("a");
    }

private:
    Chalk(const Chalk&);            // no implementation
};

struct Cheese
{
    std::string name;

    Cheese()
    {
        clog.append("e");
    }

    ~Cheese()
    {
        dlog.insert("e");
    }

private:
    Cheese(const Cheese&);          // no implementation
};

struct Chowdah
{
    char displace[17];
    std::string name;

    Chowdah()
    {
        displace[0] = '\0';
        clog.append("o");
    }

    ~Chowdah()
    {
        dlog.insert("o");
    }

private:
    Chowdah(const Chowdah&);        // no implementation
};

/*****************************************************************************
*   TUT
*****************************************************************************/
namespace tut
{
    using tut_compat::ensure;
    using tut_compat::ensure_equals;
    using tut_compat::ensure_not;
    using tut_compat::ensure_throws;

        struct llheteromap_data
        {
            llheteromap_data()
            {
                clog.erase();
                dlog.clear();
            }
        };
} // namespace tut // namespace tut

TUT_SUITE("llheteromap")
{
    TUT_CASE("llheteromap_test::create, get, delete")
    {
        using namespace tut;
        TUT_SET_TEST_NAME("create, get, delete");

        {
            LLHeteroMap map;

            {
                // create each instance
                Chalk& chalk = map.obtain<Chalk>();
                chalk.name = "Chalk";

                Cheese& cheese = map.obtain<Cheese>();
                cheese.name = "Cheese";

                Chowdah& chowdah = map.obtain<Chowdah>();
                chowdah.name = "Chowdah";
            } // refs go out of scope

            {
                // verify each instance
                Chalk& chalk = map.obtain<Chalk>();
                TUT_ENSURE_EQ(chalk.name, "Chalk");

                Cheese& cheese = map.obtain<Cheese>();
                TUT_ENSURE_EQ(cheese.name, "Cheese");

                Chowdah& chowdah = map.obtain<Chowdah>();
                TUT_ENSURE_EQ(chowdah.name, "Chowdah");
            }
        } // destroy map

        // Chalk, Cheese and Chowdah should have been created in specific order
        TUT_ENSURE_EQ(clog, "aeo");

        // We don't care what order they're destroyed in, as long as each is
        // appropriately destroyed.
        std::set<std::string> dtorset;
        for (const char* cp = "aeo"; *cp; ++cp)
            dtorset.insert(std::string(1, *cp));
        TUT_ENSURE_EQ(dlog, dtorset);
    }
}
