// ---------------------------------------------------------------------------
// Auto-generated from llinstancetracker_test.cpp at 2025-10-16T20:37:40+00:00
// Generated by gen_tut_to_doctest.py
// ---------------------------------------------------------------------------
#include "doctest.h"
#include "indra/test/ll_doctest_helpers.h"
#include "indra/test/tut_compat_doctest.h"
#include "linden_common.h"
#include "llinstancetracker.h"
#include <string>
#include <vector>
#include <set>
#include <stdexcept>

/**
 * @file   llinstancetracker_test.cpp
 * @author Nat Goodspeed
 * @date   2009-11-10
 * @brief  Test for llinstancetracker.
 *
 * $LicenseInfo:firstyear=2009&license=viewerlgpl$
 * Second Life Viewer Source Code
 * Copyright (C) 2010, Linden Research, Inc.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation;
 * version 2.1 of the License only.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 * Linden Research, Inc., 945 Battery Street, San Francisco, CA  94111  USA
 * $/LicenseInfo$
 */

// Precompiled header
// associated header
// STL headers
// std headers
// other Linden headers

struct Badness: public std::runtime_error
{
    Badness(const std::string& what): std::runtime_error(what) {}
};

struct Keyed: public LLInstanceTracker<Keyed, std::string>
{
    Keyed(const std::string& name):
        LLInstanceTracker<Keyed, std::string>(name),
        mName(name)
    {}
    std::string mName;
};

struct Unkeyed: public LLInstanceTracker<Unkeyed>
{
    Unkeyed(const std::string& thrw="")
    {
        // LLInstanceTracker should respond appropriately if a subclass
        // constructor throws an exception. Specifically, it should run
        // LLInstanceTracker's destructor and remove itself from the
        // underlying container.
        if (! thrw.empty())
        {
            throw Badness(thrw);
        }
    }
};

/*****************************************************************************
*   TUT
*****************************************************************************/
namespace tut
{
    using tut_compat::ensure;
    using tut_compat::ensure_equals;
    using tut_compat::ensure_not;
    using tut_compat::ensure_throws;

        struct llinstancetracker_data
        {
        };
} // namespace tut // namespace tut

TUT_SUITE("llinstancetracker")
{
    TUT_CASE("llinstancetracker_test::object_test_1")
    {
        using namespace tut;
        TUT_ENSURE_EQ(Keyed::instanceCount(), 0);
        {
            Keyed one("one");
            TUT_ENSURE_EQ(Keyed::instanceCount(), 1);
            auto found = Keyed::getInstance("one");
            TUT_CHECK_MSG(bool(found), "couldn't find stack Keyed");
            TUT_ENSURE_EQ("found wrong Keyed instance", found.get(), &one);
            {
                std::unique_ptr<Keyed> two(new Keyed("two"));
                TUT_ENSURE_EQ(Keyed::instanceCount(), 2);
                auto found = Keyed::getInstance("two");
                TUT_CHECK_MSG(bool(found), "couldn't find heap Keyed");
                TUT_ENSURE_EQ("found wrong Keyed instance", found.get(), two.get());
            }
            TUT_ENSURE_EQ(Keyed::instanceCount(), 1);
        }
        auto found = Keyed::getInstance("one");
        TUT_CHECK_MSG(! found, "Keyed key lives too long");
        TUT_ENSURE_EQ(Keyed::instanceCount(), 0);
    }

    TUT_CASE("llinstancetracker_test::object_test_2")
    {
        using namespace tut;
        TUT_ENSURE_EQ(Unkeyed::instanceCount(), 0);
        std::weak_ptr<Unkeyed> dangling;
        {
            Unkeyed one;
            TUT_ENSURE_EQ(Unkeyed::instanceCount(), 1);
            std::weak_ptr<Unkeyed> found = one.getWeak();
            TUT_ENSURE(! found.expired());
            {
                std::unique_ptr<Unkeyed> two(new Unkeyed);
                TUT_ENSURE_EQ(Unkeyed::instanceCount(), 2);
            }
            TUT_ENSURE_EQ(Unkeyed::instanceCount(), 1);
            // store a weak pointer to a temp Unkeyed instance
            dangling = found;
        } // make that instance vanish
        // check the now-invalid pointer to the destroyed instance
        TUT_CHECK_MSG(dangling.expired(), "weak_ptr<Unkeyed> failed to track destruction");
        TUT_ENSURE_EQ(Unkeyed::instanceCount(), 0);
    }

    TUT_CASE("llinstancetracker_test::object_test_3")
    {
        using namespace tut;
        Keyed one("one"), two("two"), three("three");
        // We don't want to rely on the underlying container delivering keys
        // in any particular order. That allows us the flexibility to
        // reimplement LLInstanceTracker using, say, a hash map instead of a
        // std::map. We DO insist that every key appear exactly once.
        typedef std::vector<std::string> StringVector;
        auto snap = Keyed::key_snapshot();
        StringVector keys(snap.begin(), snap.end());
        std::sort(keys.begin(), keys.end());
        StringVector::const_iterator ki(keys.begin());
        TUT_ENSURE_EQ(*ki++, "one");
        TUT_ENSURE_EQ(*ki++, "three");
        TUT_ENSURE_EQ(*ki++, "two");
        // Use ensure() here because ensure_equals would want to display
        // mismatched values, and frankly that wouldn't help much.
        TUT_CHECK_MSG(ki == keys.end(), "didn't reach end");

        // Use a somewhat different approach to order independence with
        // instance_snapshot(): explicitly capture the instances we know in a
        // set, and delete them as we iterate through.
        typedef std::set<Keyed*> InstanceSet;
        InstanceSet instances;
        instances.insert(&one);
        instances.insert(&two);
        instances.insert(&three);
        for (auto& ref : Keyed::instance_snapshot())
        {
            TUT_ENSURE_EQ("spurious instance", instances.erase(&ref), 1);
        }
        TUT_ENSURE_EQ("unreported instance", instances.size(), 0);
    }

    TUT_CASE("llinstancetracker_test::object_test_4")
    {
        using namespace tut;
        Unkeyed one, two, three;
        typedef std::set<Unkeyed*> KeySet;

        KeySet instances;
        instances.insert(&one);
        instances.insert(&two);
        instances.insert(&three);

        for (auto& ref : Unkeyed::instance_snapshot())
        {
            TUT_ENSURE_EQ("spurious instance", instances.erase(&ref), 1);
        }

        TUT_ENSURE_EQ("unreported instance", instances.size(), 0);
    }

    TUT_CASE("llinstancetracker_test::object_test_5")
    {
        using namespace tut;
        std::string desc("delete Keyed with outstanding instance_snapshot");
        TUT_SET_TEST_NAME(desc);
        Keyed* keyed = new Keyed(desc);
        // capture a snapshot but do not yet traverse it
        auto snapshot = Keyed::instance_snapshot();
        // delete the one instance
        delete keyed;
        // traversing the snapshot should reflect the deletion
        // avoid ensure_equals() because it requires the ability to stream the
        // two values to std::ostream
        TUT_ENSURE(snapshot.begin() == snapshot.end());
    }

    TUT_CASE("llinstancetracker_test::object_test_6")
    {
        using namespace tut;
        std::string desc("delete Keyed with outstanding key_snapshot");
        TUT_SET_TEST_NAME(desc);
        Keyed* keyed = new Keyed(desc);
        // capture a snapshot but do not yet traverse it
        auto snapshot = Keyed::key_snapshot();
        // delete the one instance
        delete keyed;
        // traversing the snapshot should reflect the deletion
        // avoid ensure_equals() because it requires the ability to stream the
        // two values to std::ostream
        TUT_ENSURE(snapshot.begin() == snapshot.end());
    }

    TUT_CASE("llinstancetracker_test::delete Unkeyed with outstanding instance_snapshot")
    {
        using namespace tut;
        TUT_SET_TEST_NAME("delete Unkeyed with outstanding instance_snapshot");
        std::string what;
        Unkeyed* unkeyed = new Unkeyed;
        // capture a snapshot but do not yet traverse it
        auto snapshot = Unkeyed::instance_snapshot();
        // delete the one instance
        delete unkeyed;
        // traversing the snapshot should reflect the deletion
        // avoid ensure_equals() because it requires the ability to stream the
        // two values to std::ostream
        TUT_ENSURE(snapshot.begin() == snapshot.end());
    }

    TUT_CASE("llinstancetracker_test::exception in subclass ctor")
    {
        using namespace tut;
        TUT_SET_TEST_NAME("exception in subclass ctor");
        typedef std::set<Unkeyed*> InstanceSet;
        InstanceSet existing;
        // We can't use the iterator-range InstanceSet constructor because
        // beginInstances() returns an iterator that dereferences to an
        // Unkeyed&, not an Unkeyed*.
        for (auto& ref : Unkeyed::instance_snapshot())
        {
            existing.insert(&ref);
        }
        try
        {
            // We don't expect the assignment to take place because we expect
            // Unkeyed to respond to the non-empty string param by throwing.
            // We know the LLInstanceTracker base-class constructor will have
            // run before Unkeyed's constructor, therefore the new instance
            // will have added itself to the underlying set. The whole
            // question is, when Unkeyed's constructor throws, will
            // LLInstanceTracker's destructor remove it from the set? I
            // realize we're testing the C++ implementation more than
            // Unkeyed's implementation, but this seems an important point to
            // nail down.
            new Unkeyed("throw");
        }
        catch (const Badness&)
        {
        }
        // Ensure that every member of the new, updated set of Unkeyed
        // instances was also present in the original set. If that's not true,
        // it's because our new Unkeyed ended up in the updated set despite
        // its constructor exception.
        for (auto& ref : Unkeyed::instance_snapshot())
        {
            TUT_CHECK_MSG(existing.find(&ref) != existing.end(), "failed to remove instance");
        }
    }
}
