// ---------------------------------------------------------------------------
// Auto-generated from llmainthreadtask_test.cpp at 2025-10-16T20:37:40+00:00
// Generated by gen_tut_to_doctest.py
// ---------------------------------------------------------------------------
#include "doctest.h"
#include "indra/test/ll_doctest_helpers.h"
#include "indra/test/tut_compat_doctest.h"
#include "linden_common.h"
#include "llmainthreadtask.h"
#include <atomic>
#include "../test/sync.h"
#include "lleventtimer.h"
#include "lockstatic.h"

/**
 * @file   llmainthreadtask_test.cpp
 * @author Nat Goodspeed
 * @date   2019-12-05
 * @brief  Test for llmainthreadtask.
 *
 * $LicenseInfo:firstyear=2019&license=viewerlgpl$
 * Copyright (c) 2019, Linden Research, Inc.
 * $/LicenseInfo$
 */

// Precompiled header
// associated header
// STL headers
// std headers
// external library headers
// other Linden headers

/*****************************************************************************
*   TUT
*****************************************************************************/
namespace tut
{
    using tut_compat::ensure;
    using tut_compat::ensure_equals;
    using tut_compat::ensure_not;
    using tut_compat::ensure_throws;

        struct llmainthreadtask_data
        {
            // 5-second timeout
            Sync mSync{F32Milliseconds(5000.0f)};

            llmainthreadtask_data()
            {
                // we're not testing the result; this is just to cache the
                // initial thread as the main thread.
                on_main_thread();
            }
        };



        struct StaticData
        {
            std::mutex mMutex;          // LockStatic looks for mMutex
            bool ran{false};
        };
        typedef llthread::LockStatic<StaticData> LockStatic;
} // namespace tut // namespace tut

TUT_SUITE("llmainthreadtask")
{
    TUT_CASE("llmainthreadtask_test::inline")
    {
        using namespace tut;
        TUT_SET_TEST_NAME("inline");
        bool ran = false;
        bool result = LLMainThreadTask::dispatch(
            [&ran]()->bool{
                ran = true;
                return true;
            });
        TUT_CHECK_MSG(ran, "didn't run lambda");
        TUT_CHECK_MSG(result, "didn't return result");
    }

    TUT_CASE("llmainthreadtask_test::cross-thread")
    {
        using namespace tut;
        TUT_SET_TEST_NAME("cross-thread");
        TUT_SKIP("This test is prone to build-time hangs");
        std::atomic_bool result(false);
        // wrapping our thread lambda in a packaged_task will catch any
        // exceptions it might throw and deliver them via future
        std::packaged_task<void()> thread_work(
            [this, &result](){
                // unblock test<2>()'s yield_until(1)
                mSync.set(1);
                // dispatch work to main thread -- should block here
                bool on_main(
                    LLMainThreadTask::dispatch(
                        []()->bool{
                            // have to lock static mutex to set static data
                            LockStatic()->ran = true;
                            // indicate whether task was run on the main thread
                            return on_main_thread();
                        }));
                // wait for test<2>() to unblock us again
                mSync.yield_until(3);
                result = on_main;
            });
        auto thread_result = thread_work.get_future();
        std::thread thread;
        try
        {
            // run thread_work
            thread = std::thread(std::move(thread_work));
            // wait for thread to set(1)
            mSync.yield_until(1);
            // try to acquire the lock, should block because thread has it
            LockStatic lk;
            // wake up when dispatch() unlocks the static mutex
            TUT_CHECK_MSG(!lk->ran, "shouldn't have run yet");
            TUT_CHECK_MSG(!result, "shouldn't have returned yet");
            // unlock so the task can acquire the lock
            lk.unlock();
            // run the task -- should unblock thread, which will immediately block
            // on mSync
            LLEventTimer::updateClass();
            // 'lk', having unlocked, can no longer be used to access; relock with
            // a new LockStatic instance
            TUT_CHECK_MSG(LockStatic()->ran, "should now have run");
            TUT_CHECK_MSG(!result, "returned too early");
            // okay, let thread perform the assignment
            mSync.set(3);
        }
        catch (...)
        {
            // A test failure exception anywhere in the try block can cause
            // the test program to terminate without explanation when
            // ~thread() finds that 'thread' is still joinable. We could
            // either join() or detach() it -- but since it might be blocked
            // waiting for something from the main thread that now can never
            // happen, it's safer to detach it.
            thread.detach();
            throw;
        }
        // 'thread' should be all done now
        thread.join();
        // deliver any exception thrown by thread_work
        thread_result.get();
        TUT_CHECK_MSG(LockStatic()->ran, "ran changed");
        TUT_CHECK_MSG(result, "didn't run on main thread");
    }
}
