// ---------------------------------------------------------------------------
// Auto-generated from llpounceable_test.cpp at 2025-10-16T20:37:40+00:00
// Generated by gen_tut_to_doctest.py
// ---------------------------------------------------------------------------
#include "doctest.h"
#include "indra/test/ll_doctest_helpers.h"
#include "indra/test/tut_compat_doctest.h"
#include "linden_common.h"
#include "llpounceable.h"
#include <boost/bind.hpp>

/**
 * @file   llpounceable_test.cpp
 * @author Nat Goodspeed
 * @date   2015-05-22
 * @brief  Test for llpounceable.
 *
 * $LicenseInfo:firstyear=2015&license=viewerlgpl$
 * Copyright (c) 2015, Linden Research, Inc.
 * $/LicenseInfo$
 */

// Precompiled header
// associated header
// STL headers
// std headers
// external library headers
// other Linden headers

/*----------------------------- string testing -----------------------------*/
void append(std::string* dest, const std::string& src)
{
    dest->append(src);
}

/*-------------------------- Data-struct testing ---------------------------*/
struct Data
{
    Data(const std::string& data):
        mData(data)
    {}
    const std::string mData;
};

void setter(Data** dest, Data* ptr)
{
    *dest = ptr;
}

static Data* static_check = 0;

// Set up an extern pointer to an LLPounceableStatic so the linker will fill
// in the forward reference from below, before runtime.
extern LLPounceable<Data*, LLPounceableStatic> gForward;

struct EnqueueCall
{
    EnqueueCall()
    {
        // Intentionally use a forward reference to an LLPounceableStatic that
        // we believe is NOT YET CONSTRUCTED. This models the scenario in
        // which a constructor in another translation unit runs before
        // constructors in this one. We very specifically want callWhenReady()
        // to work even in that case: we need the LLPounceableQueueImpl to be
        // initialized even if the LLPounceable itself is not.
        gForward.callWhenReady(boost::bind(setter, &static_check, _1));
    }
} nqcall;
// When this declaration is processed, we should enqueue the
// setter(&static_check, _1) call for when gForward is set non-NULL. Needless
// to remark, we want this call not to crash.

// Now declare gForward. Its constructor should not run until after nqcall's.
LLPounceable<Data*, LLPounceableStatic> gForward;

/*****************************************************************************
*   TUT
*****************************************************************************/
namespace tut
{
    using tut_compat::ensure;
    using tut_compat::ensure_equals;
    using tut_compat::ensure_not;
    using tut_compat::ensure_throws;

        struct llpounceable_data
        {
        };
} // namespace tut // namespace tut

TUT_SUITE("llpounceable")
{
    TUT_CASE("llpounceable_test::LLPounceableStatic out-of-order test")
    {
        using namespace tut;
        TUT_SET_TEST_NAME("LLPounceableStatic out-of-order test");
        // LLPounceable<T, LLPounceableStatic>::callWhenReady() must work even
        // before LLPounceable's constructor runs. That's the whole point of
        // implementing it with an LLSingleton queue. This models (say)
        // LLPounceableStatic<LLMessageSystem*, LLPounceableStatic>.
        TUT_CHECK_MSG(! static_check, "static_check should still be null");
        Data myData("test<1>");
        gForward = &myData;         // should run setter
        TUT_ENSURE_EQ("static_check should be &myData", static_check, &myData);
    }

    TUT_CASE("llpounceable_test::LLPounceableQueue different queues")
    {
        using namespace tut;
        TUT_SET_TEST_NAME("LLPounceableQueue different queues");
        // We expect that LLPounceable<T, LLPounceableQueue> should have
        // different queues because that specialization stores the queue
        // directly in the LLPounceable instance.
        Data *aptr = 0, *bptr = 0;
        LLPounceable<Data*> a, b;
        a.callWhenReady(boost::bind(setter, &aptr, _1));
        b.callWhenReady(boost::bind(setter, &bptr, _1));
        TUT_CHECK_MSG(! aptr, "aptr should be null");
        TUT_CHECK_MSG(! bptr, "bptr should be null");
        Data adata("a"), bdata("b");
        a = &adata;
        TUT_ENSURE_EQ("aptr should be &adata", aptr, &adata);
        // but we haven't yet set b
        TUT_CHECK_MSG(!bptr, "bptr should still be null");
        b = &bdata;
        TUT_ENSURE_EQ("bptr should be &bdata", bptr, &bdata);
    }

    TUT_CASE("llpounceable_test::LLPounceableStatic different queues")
    {
        using namespace tut;
        TUT_SET_TEST_NAME("LLPounceableStatic different queues");
        // LLPounceable<T, LLPounceableStatic> should also have a distinct
        // queue for each instance, but that engages an additional map lookup
        // because there's only one LLSingleton for each T.
        Data *aptr = 0, *bptr = 0;
        LLPounceable<Data*, LLPounceableStatic> a, b;
        a.callWhenReady(boost::bind(setter, &aptr, _1));
        b.callWhenReady(boost::bind(setter, &bptr, _1));
        TUT_CHECK_MSG(! aptr, "aptr should be null");
        TUT_CHECK_MSG(! bptr, "bptr should be null");
        Data adata("a"), bdata("b");
        a = &adata;
        TUT_ENSURE_EQ("aptr should be &adata", aptr, &adata);
        // but we haven't yet set b
        TUT_CHECK_MSG(!bptr, "bptr should still be null");
        b = &bdata;
        TUT_ENSURE_EQ("bptr should be &bdata", bptr, &bdata);
    }

    TUT_CASE("llpounceable_test::LLPounceable<T> looks like T")
    {
        using namespace tut;
        TUT_SET_TEST_NAME("LLPounceable<T> looks like T");
        // We want LLPounceable<T, TAG> to be drop-in replaceable for a plain
        // T for read constructs. In particular, it should behave like a dumb
        // pointer -- and with zero abstraction cost for such usage.
        Data* aptr = 0;
        Data a("a");
        // should be able to initialize a pounceable (when its constructor
        // runs)
        LLPounceable<Data*> pounceable(&a);
        // should be able to pass LLPounceable<T> to function accepting T
        setter(&aptr, pounceable);
        TUT_ENSURE_EQ("aptr should be &a", aptr, &a);
        // should be able to dereference with *
        TUT_ENSURE_EQ("deref with *", (*pounceable).mData, "a");
        // should be able to dereference with ->
        TUT_ENSURE_EQ("deref with ->", pounceable->mData, "a");
        // bool operations
        TUT_CHECK_MSG(pounceable, "test with operator bool()");
        TUT_CHECK_MSG(! (! pounceable), "test with operator !()");
    }

    TUT_CASE("llpounceable_test::Multiple callWhenReady() queue items")
    {
        using namespace tut;
        TUT_SET_TEST_NAME("Multiple callWhenReady() queue items");
        Data *p1 = 0, *p2 = 0, *p3 = 0;
        Data a("a");
        LLPounceable<Data*> pounceable;
        // queue up a couple setter() calls for later
        pounceable.callWhenReady(boost::bind(setter, &p1, _1));
        pounceable.callWhenReady(boost::bind(setter, &p2, _1));
        // should still be pending
        TUT_CHECK_MSG(!p1, "p1 should be null");
        TUT_CHECK_MSG(!p2, "p2 should be null");
        TUT_CHECK_MSG(!p3, "p3 should be null");
        pounceable = 0;
        // assigning a new empty value shouldn't flush the queue
        TUT_CHECK_MSG(!p1, "p1 should still be null");
        TUT_CHECK_MSG(!p2, "p2 should still be null");
        TUT_CHECK_MSG(!p3, "p3 should still be null");
        // using whichever syntax
        pounceable.reset(0);
        // try to make ensure messages distinct... tough to pin down which
        // ensure() failed if multiple ensure() calls in the same test<n> have
        // the same message!
        TUT_CHECK_MSG(!p1, "p1 should again be null");
        TUT_CHECK_MSG(!p2, "p2 should again be null");
        TUT_CHECK_MSG(!p3, "p3 should again be null");
        pounceable.reset(&a);       // should flush queue
        TUT_ENSURE_EQ("p1 should be &a", p1, &a);
        TUT_ENSURE_EQ("p2 should be &a", p2, &a);
        TUT_CHECK_MSG(!p3, "p3 still not set");
        // immediate call
        pounceable.callWhenReady(boost::bind(setter, &p3, _1));
        TUT_ENSURE_EQ("p3 should be &a", p3, &a);
    }

    TUT_CASE("llpounceable_test::queue order")
    {
        using namespace tut;
        TUT_SET_TEST_NAME("queue order");
        std::string data;
        LLPounceable<std::string*> pounceable;
        pounceable.callWhenReady(boost::bind(append, _1, "a"));
        pounceable.callWhenReady(boost::bind(append, _1, "b"));
        pounceable.callWhenReady(boost::bind(append, _1, "c"));
        pounceable = &data;
        TUT_ENSURE_EQ("callWhenReady() must preserve chronological order", data, "abc");

        std::string data2;
        pounceable = NULL;
        pounceable.callWhenReady(boost::bind(append, _1, "d"));
        pounceable.callWhenReady(boost::bind(append, _1, "e"));
        pounceable.callWhenReady(boost::bind(append, _1, "f"));
        pounceable = &data2;
        TUT_ENSURE_EQ("LLPounceable must reset queue when fired", data2, "def");
    }

    TUT_CASE("llpounceable_test::compile-fail test, uncomment to check")
    {
        using namespace tut;
                TUT_SET_TEST_NAME("compile-fail test, uncomment to check");
                // The following declaration should fail: only LLPounceableQueue and
                // LLPounceableStatic should work as tags.
        //      LLPounceable<Data*, int> pounceable;
    }
}
