// ---------------------------------------------------------------------------
// Auto-generated from llprocinfo_test.cpp at 2025-10-16T20:37:40+00:00
// Generated by gen_tut_to_doctest.py
// ---------------------------------------------------------------------------
#include "doctest.h"
#include "indra/test/ll_doctest_helpers.h"
#include "indra/test/tut_compat_doctest.h"
#include "linden_common.h"
#include "../llprocinfo.h"
#include "../lltimer.h"

/**
 * @file llprocinfo_test.cpp
 * @brief Tests for the LLProcInfo class.
 *
 * $LicenseInfo:firstyear=2013&license=viewerlgpl$
 * Second Life Viewer Source Code
 * Copyright (C) 2013, Linden Research, Inc.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation;
 * version 2.1 of the License only.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 * Linden Research, Inc., 945 Battery Street, San Francisco, CA  94111  USA
 * $/LicenseInfo$
 */





static const LLProcInfo::time_type bad_user(289375U), bad_system(275U);


namespace tut
{
    using tut_compat::ensure;
    using tut_compat::ensure_equals;
    using tut_compat::ensure_not;
    using tut_compat::ensure_throws;

    struct procinfo_test
    {
        procinfo_test()
            {
            }
    };



    // Basic invocation works



    // Time increases
} // namespace tut // end namespace tut

TUT_SUITE("llprocinfo_test")
{
    TUT_CASE("llprocinfo_test::getCPUUsage() basic function")
    {
        using namespace tut;
        LLProcInfo::time_type user(bad_user), system(bad_system);

        TUT_SET_TEST_NAME("getCPUUsage() basic function");

        LLProcInfo::getCPUUsage(user, system);

        TUT_CHECK_MSG((user) != (bad_user), "getCPUUsage() writes to its user argument");
        TUT_CHECK_MSG((system) != (bad_system), "getCPUUsage() writes to its system argument");
    }

    TUT_CASE("llprocinfo_test::getCPUUsage() increases over time")
    {
        using namespace tut;
        LLProcInfo::time_type user(bad_user), system(bad_system);
        LLProcInfo::time_type user2(bad_user), system2(bad_system);

        TUT_SET_TEST_NAME("getCPUUsage() increases over time");

        LLProcInfo::getCPUUsage(user, system);

        for (int i(0); i < 100000; ++i)
        {
            ms_sleep(0);
        }

        LLProcInfo::getCPUUsage(user2, system2);

        TUT_ENSURE_EQ("getCPUUsage() user value doesn't decrease over time", user2 >= user, true);
        TUT_ENSURE_EQ("getCPUUsage() system value doesn't decrease over time", system2 >= system, true);
    }
}
