// ---------------------------------------------------------------------------
// Auto-generated from llprocessor_test.cpp at 2025-10-16T20:37:40+00:00
// Generated by gen_tut_to_doctest.py
// ---------------------------------------------------------------------------
#include "doctest.h"
#include "indra/test/ll_doctest_helpers.h"
#include "indra/test/tut_compat_doctest.h"
#include "linden_common.h"
#include "../llprocessor.h"

/**
 * @file llprocessor_test.cpp
 * @date 2010-06-01
 *
 * $LicenseInfo:firstyear=2010&license=viewerlgpl$
 * Second Life Viewer Source Code
 * Copyright (C) 2010, Linden Research, Inc.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation;
 * version 2.1 of the License only.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 * Linden Research, Inc., 945 Battery Street, San Francisco, CA  94111  USA
 * $/LicenseInfo$
 */




namespace tut
{
    using tut_compat::ensure;
    using tut_compat::ensure_equals;
    using tut_compat::ensure_not;
    using tut_compat::ensure_throws;

        struct processor
        {
        };
} // namespace tut

TUT_SUITE("llprocessor_test")
{
    TUT_CASE("llprocessor_test::LLProcessorInfo regression test")
    {
        using namespace tut;
        TUT_SET_TEST_NAME("LLProcessorInfo regression test");

        LLProcessorInfo pi;
        F64 freq =  pi.getCPUFrequency();
        //bool sse =  pi.hasSSE();
        //bool sse2 = pi.hasSSE2();
        //bool alitvec = pi.hasAltivec();
        std::string family = pi.getCPUFamilyName();
        std::string brand =  pi.getCPUBrandName();
        //std::string steam =  pi.getCPUFeatureDescription();

        TUT_CHECK_MSG((brand) != ("Unknown"), "Unknown Brand name");
        TUT_CHECK_MSG((family) != ("Unknown"), "Unknown Family name");
        TUT_CHECK_MSG(freq > 100 && freq < 10000, "Reasonable CPU Frequency > 100 && < 10000");
    }
}
