// ---------------------------------------------------------------------------
// Auto-generated from llrand_test.cpp at 2025-10-16T20:37:40+00:00
// Generated by gen_tut_to_doctest.py
// ---------------------------------------------------------------------------
#include "doctest.h"
#include "indra/test/ll_doctest_helpers.h"
#include "indra/test/tut_compat_doctest.h"
#include "linden_common.h"
#include "../llrand.h"
#include "stringize.h"

/**
 * @file llrandom_test.cpp
 * @author Phoenix
 * @date 2007-01-25
 *
 * $LicenseInfo:firstyear=2007&license=viewerlgpl$
 * Second Life Viewer Source Code
 * Copyright (C) 2010, Linden Research, Inc.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation;
 * version 2.1 of the License only.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 * Linden Research, Inc., 945 Battery Street, San Francisco, CA  94111  USA
 * $/LicenseInfo$
 */



// In llrand.h, every function is documented to return less than the high end
// -- specifically, because you can pass a negative extent, they're documented
// never to return a value equal to the extent.
// So that we don't need two different versions of ensure_in_range(), when
// testing extent < 0, negate the return value and the extent before passing
// into ensure_in_range().
template <typename NUMBER>
void ensure_in_range(const std::string_view& name,
                     NUMBER value, NUMBER low, NUMBER high)
{
    auto failmsg{ stringize(name, " >= ", low, " (", value, ')') };
    tut_compat::ensure(failmsg.c_str(), (value >= low));
    failmsg = stringize(name, " < ", high, " (", value, ')');
    tut_compat::ensure(failmsg.c_str(), (value < high));
}

namespace tut
{
    using tut_compat::ensure;
    using tut_compat::ensure_equals;
    using tut_compat::ensure_not;
    using tut_compat::ensure_throws;

        struct random
        {
        };
} // namespace tut

TUT_SUITE("llrand_test")
{
    TUT_CASE("llrand_test::random_object_t_test_1")
    {
        using namespace tut;
        for(S32 ii = 0; ii < 100000; ++ii)
        {
            do { INFO("frand"); TUT_ENSURE_IN_RANGE(ll_frand(), 0.0f, 1.0f); } while (false);
        }
    }

    TUT_CASE("llrand_test::random_object_t_test_2")
    {
        using namespace tut;
        for(S32 ii = 0; ii < 100000; ++ii)
        {
            do { INFO("drand"); TUT_ENSURE_IN_RANGE(ll_drand(), 0.0, 1.0); } while (false);
        }
    }

    TUT_CASE("llrand_test::random_object_t_test_3")
    {
        using namespace tut;
        for(S32 ii = 0; ii < 100000; ++ii)
        {
            do { INFO("frand(2.0f)"); TUT_ENSURE_IN_RANGE(ll_frand(2.0f) - 1.0f, -1.0f, 1.0f); } while (false);
        }
    }

    TUT_CASE("llrand_test::random_object_t_test_4")
    {
        using namespace tut;
        for(S32 ii = 0; ii < 100000; ++ii)
        {
            // Negate the result so we don't have to allow a templated low-end
            // comparison as well.
            do { INFO("-frand(-7.0)"); TUT_ENSURE_IN_RANGE(-ll_frand(-7.0), 0.0f, 7.0f); } while (false);
        }
    }

    TUT_CASE("llrand_test::random_object_t_test_5")
    {
        using namespace tut;
        for(S32 ii = 0; ii < 100000; ++ii)
        {
            do { INFO("-drand(-2.0)"); TUT_ENSURE_IN_RANGE(-ll_drand(-2.0), 0.0, 2.0); } while (false);
        }
    }

    TUT_CASE("llrand_test::random_object_t_test_6")
    {
        using namespace tut;
        for(S32 ii = 0; ii < 100000; ++ii)
        {
            do { INFO("rand(100)"); TUT_ENSURE_IN_RANGE(ll_rand(100), 0, 100); } while (false);
        }
    }

    TUT_CASE("llrand_test::random_object_t_test_7")
    {
        using namespace tut;
        for(S32 ii = 0; ii < 100000; ++ii)
        {
            do { INFO("-rand(-127)"); TUT_ENSURE_IN_RANGE(-ll_rand(-127), 0, 127); } while (false);
        }
    }
}
