// ---------------------------------------------------------------------------
// Auto-generated from llstreamqueue_test.cpp at 2025-10-16T20:37:40+00:00
// Generated by gen_tut_to_doctest.py
// ---------------------------------------------------------------------------
#include "doctest.h"
#include "indra/test/ll_doctest_helpers.h"
#include "indra/test/tut_compat_doctest.h"
#include "linden_common.h"
#include "llstreamqueue.h"
#include <vector>
#include "stringize.h"

/**
 * @file   llstreamqueue_test.cpp
 * @author Nat Goodspeed
 * @date   2012-01-05
 * @brief  Test for llstreamqueue.
 *
 * $LicenseInfo:firstyear=2012&license=viewerlgpl$
 * Copyright (c) 2012, Linden Research, Inc.
 * $/LicenseInfo$
 */

// Precompiled header
// associated header
// STL headers
// other Linden headers

/*****************************************************************************
*   TUT
*****************************************************************************/
namespace tut
{
    using tut_compat::ensure;
    using tut_compat::ensure_equals;
    using tut_compat::ensure_not;
    using tut_compat::ensure_throws;

        struct llstreamqueue_data
        {
            llstreamqueue_data():
                // we want a buffer with actual bytes in it, not an empty vector
                buffer(10)
            {}
            // As LLStreamQueue is merely a typedef for
            // LLGenericStreamQueue<char>, and no logic in LLGenericStreamQueue is
            // specific to the <char> instantiation, we're comfortable for now
            // testing only the narrow-char version.
            LLStreamQueue strq;
            // buffer for use in multiple tests
            std::vector<char> buffer;
        };
} // namespace tut // namespace tut

TUT_SUITE("llstreamqueue")
{
    TUT_CASE("llstreamqueue_test::empty LLStreamQueue")
    {
        using namespace tut;
        TUT_SET_TEST_NAME("empty LLStreamQueue");
        TUT_ENSURE_EQ("brand-new LLStreamQueue isn't empty", strq.size(), 0);
        TUT_ENSURE_EQ("brand-new LLStreamQueue returns data", strq.asSource().read(&buffer[0], buffer.size()), 0);
        strq.asSink().close();
        TUT_ENSURE_EQ("closed empty LLStreamQueue not at EOF", strq.asSource().read(&buffer[0], buffer.size()), -1);
    }

    TUT_CASE("llstreamqueue_test::one internal block, one buffer")
    {
        using namespace tut;
        TUT_SET_TEST_NAME("one internal block, one buffer");
        LLStreamQueue::Sink sink(strq.asSink());
        TUT_ENSURE_EQ("write(\"\")", sink.write("", 0), 0);
        TUT_ENSURE_EQ("0 write should leave LLStreamQueue empty (size())", strq.size(), 0);
        TUT_ENSURE_EQ("0 write should leave LLStreamQueue empty (peek())", strq.peek(&buffer[0], buffer.size()), 0);
        // The meaning of "atomic" is that it must be smaller than our buffer.
        std::string atomic("atomic");
        TUT_CHECK_MSG(atomic.length() < buffer.size(), "test data exceeds buffer");
        TUT_ENSURE_EQ(STRINGIZE("write(\"" << atomic << "\")"), sink.write(&atomic[0], atomic.length()), atomic.length());
        TUT_ENSURE_EQ("size() after write()", strq.size(), atomic.length());
        size_t peeklen(strq.peek(&buffer[0], buffer.size()));
        TUT_ENSURE_EQ(STRINGIZE("peek(\"" << atomic << "\")"), peeklen, atomic.length());
        TUT_ENSURE_EQ(STRINGIZE("peek(\"" << atomic << "\") result"), std::string(buffer.begin(), buffer.begin() + peeklen), atomic);
        TUT_ENSURE_EQ("size() after peek()", strq.size(), atomic.length());
        // peek() should not consume. Use a different buffer to prove it isn't
        // just leftover data from the first peek().
        std::vector<char> again(buffer.size());
        peeklen = size_t(strq.peek(&again[0], again.size()));
        TUT_ENSURE_EQ(STRINGIZE("peek(\"" << atomic << "\") again"), peeklen, atomic.length());
        TUT_ENSURE_EQ(STRINGIZE("peek(\"" << atomic << "\") again result"), std::string(again.begin(), again.begin() + peeklen), atomic);
        // now consume.
        std::vector<char> third(buffer.size());
        size_t readlen(strq.read(&third[0], third.size()));
        TUT_ENSURE_EQ(STRINGIZE("read(\"" << atomic << "\")"), readlen, atomic.length());
        TUT_ENSURE_EQ(STRINGIZE("read(\"" << atomic << "\") result"), std::string(third.begin(), third.begin() + readlen), atomic);
        TUT_ENSURE_EQ("peek() after read()", strq.peek(&buffer[0], buffer.size()), 0);
        TUT_ENSURE_EQ("size() after read()", strq.size(), 0);
    }

    TUT_CASE("llstreamqueue_test::basic skip()")
    {
        using namespace tut;
        TUT_SET_TEST_NAME("basic skip()");
        std::string lovecraft("lovecraft");
        TUT_CHECK_MSG(lovecraft.length() < buffer.size(), "test data exceeds buffer");
        TUT_ENSURE_EQ(STRINGIZE("write(\"" << lovecraft << "\")"), strq.write(&lovecraft[0], lovecraft.length()), lovecraft.length());
        size_t peeklen(strq.peek(&buffer[0], buffer.size()));
        TUT_ENSURE_EQ(STRINGIZE("peek(\"" << lovecraft << "\")"), peeklen, lovecraft.length());
        TUT_ENSURE_EQ(STRINGIZE("peek(\"" << lovecraft << "\") result"), std::string(buffer.begin(), buffer.begin() + peeklen), lovecraft);
        std::streamsize skip1(4);
        TUT_ENSURE_EQ(STRINGIZE("skip(" << skip1 << ")"), strq.skip(skip1), skip1);
        TUT_ENSURE_EQ("size() after skip()", strq.size(), lovecraft.length() - skip1);
        size_t readlen(strq.read(&buffer[0], buffer.size()));
        TUT_ENSURE_EQ(STRINGIZE("read(\"" << lovecraft.substr(skip1) << "\")"), readlen, lovecraft.length() - skip1);
        TUT_ENSURE_EQ(STRINGIZE("read(\"" << lovecraft.substr(skip1) << "\") result"), std::string(buffer.begin(), buffer.begin() + readlen), lovecraft.substr(skip1));
        TUT_ENSURE_EQ("unconsumed", strq.read(&buffer[0], buffer.size()), 0);
    }

    TUT_CASE("llstreamqueue_test::skip() multiple blocks")
    {
        using namespace tut;
        TUT_SET_TEST_NAME("skip() multiple blocks");
        std::string blocks[] = { "books of ", "H.P. ", "Lovecraft" };
        std::streamsize total(blocks[0].length() + blocks[1].length() + blocks[2].length());
        std::streamsize leave(5);   // len("craft") above
        std::streamsize TUT_SKIP(total - leave);
        std::streamsize written(0);
        for (const std::string& block : blocks)
        {
            written += strq.write(&block[0], block.length());
            TUT_ENSURE_EQ("size() after write()", strq.size(), written);
        }
        std::streamsize skiplen(strq.TUT_SKIP(skip));
        TUT_ENSURE_EQ(STRINGIZE("skip(" << skip << ")"), skiplen, skip);
        TUT_ENSURE_EQ("size() after skip()", strq.size(), leave);
        size_t readlen(strq.read(&buffer[0], buffer.size()));
        TUT_ENSURE_EQ("read(\"craft\")", readlen, leave);
        TUT_ENSURE_EQ("read(\"craft\") result", std::string(buffer.begin(), buffer.begin() + readlen), "craft");
    }

    TUT_CASE("llstreamqueue_test::concatenate blocks")
    {
        using namespace tut;
        TUT_SET_TEST_NAME("concatenate blocks");
        std::string blocks[] = { "abcd", "efghij", "klmnopqrs" };
        for (const std::string& block : blocks)
        {
            strq.write(&block[0], block.length());
        }
        std::vector<char> longbuffer(30);
        std::streamsize readlen(strq.read(&longbuffer[0], longbuffer.size()));
        TUT_ENSURE_EQ("read() multiple blocks", readlen, blocks[0].length() + blocks[1].length() + blocks[2].length());
        TUT_ENSURE_EQ("read() multiple blocks result", std::string(longbuffer.begin(), longbuffer.begin() + readlen), blocks[0] + blocks[1] + blocks[2]);
    }

    TUT_CASE("llstreamqueue_test::split blocks")
    {
        using namespace tut;
        TUT_SET_TEST_NAME("split blocks");
        std::string blocks[] = { "abcdefghijklm", "nopqrstuvwxyz" };
        for (const std::string& block : blocks)
        {
            strq.write(&block[0], block.length());
        }
        strq.close();
        // We've already verified what strq.size() should be at this point;
        // see above test named "skip() multiple blocks"
        std::streamsize chksize(strq.size());
        std::streamsize readlen(strq.read(&buffer[0], buffer.size()));
        TUT_ENSURE_EQ("read() 0", readlen, buffer.size());
        TUT_ENSURE_EQ("read() 0 result", std::string(buffer.begin(), buffer.end()), "abcdefghij");
        chksize -= readlen;
        TUT_ENSURE_EQ("size() after read() 0", strq.size(), chksize);
        readlen = strq.read(&buffer[0], buffer.size());
        TUT_ENSURE_EQ("read() 1", readlen, buffer.size());
        TUT_ENSURE_EQ("read() 1 result", std::string(buffer.begin(), buffer.end()), "klmnopqrst");
        chksize -= readlen;
        TUT_ENSURE_EQ("size() after read() 1", strq.size(), chksize);
        readlen = strq.read(&buffer[0], buffer.size());
        TUT_ENSURE_EQ("read() 2", readlen, chksize);
        TUT_ENSURE_EQ("read() 2 result", std::string(buffer.begin(), buffer.begin() + readlen), "uvwxyz");
        TUT_ENSURE_EQ("read() 3", strq.read(&buffer[0], buffer.size()), -1);
    }
}
