// ---------------------------------------------------------------------------
// Auto-generated from llunits_test.cpp at 2025-10-16T20:37:41+00:00
// Generated by gen_tut_to_doctest.py
// ---------------------------------------------------------------------------
#include "doctest.h"
#include "indra/test/ll_doctest_helpers.h"
#include "indra/test/tut_compat_doctest.h"
#include "linden_common.h"
#include "llunits.h"

/**
 * @file llsingleton_test.cpp
 * @date 2011-08-11
 * @brief Unit test for the LLSingleton class
 *
 * $LicenseInfo:firstyear=2011&license=viewerlgpl$
 * Second Life Viewer Source Code
 * Copyright (C) 2011, Linden Research, Inc.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation;
 * version 2.1 of the License only.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 * Linden Research, Inc., 945 Battery Street, San Francisco, CA  94111  USA
 * $/LicenseInfo$
 */



namespace LLUnits
{
    // using powers of 2 to allow strict floating point equality
    LL_DECLARE_BASE_UNIT(Quatloos, "Quat");
    LL_DECLARE_DERIVED_UNIT(Latinum, "Lat", Quatloos, / 4);
    LL_DECLARE_DERIVED_UNIT(Solari, "Sol", Latinum, * 16);
}

LL_DECLARE_UNIT_TYPEDEFS(LLUnits, Quatloos);
LL_DECLARE_UNIT_TYPEDEFS(LLUnits, Latinum);
LL_DECLARE_UNIT_TYPEDEFS(LLUnits, Solari);

namespace LLUnits
{
    LL_DECLARE_BASE_UNIT(Celcius, "c");
    LL_DECLARE_DERIVED_UNIT(Fahrenheit, "f", Celcius, * 9 / 5 + 32);
    LL_DECLARE_DERIVED_UNIT(Kelvin, "k", Celcius, + 273.15f);
}

LL_DECLARE_UNIT_TYPEDEFS(LLUnits, Celcius);
LL_DECLARE_UNIT_TYPEDEFS(LLUnits, Fahrenheit);
LL_DECLARE_UNIT_TYPEDEFS(LLUnits, Kelvin);


namespace tut
{
    using tut_compat::ensure;
    using tut_compat::ensure_equals;
    using tut_compat::ensure_not;
    using tut_compat::ensure_throws;

        using namespace LLUnits;
        struct units
        {
        };


        // storage type conversions


        // conversions to/from base unit


        // conversions across non-base units


        // math operations


        // comparison operators


        bool accept_explicit_quatloos(S32Quatloos q)
        {
            return true;
        }

        bool accept_implicit_quatloos(S32Quatloos q)
        {
            return true;
        }

        // signature compatibility


        // implicit units


        // precision tests


        // default units


        bool value_near(F32 value, F32 target, F32 threshold)
        {
            return fabsf(value - target) < threshold;
        }

        // linear transforms
} // namespace tut

TUT_SUITE("llunits_test")
{
    TUT_CASE("llunits_test::units_object_t_test_1")
    {
        using namespace tut;
        LLUnit<F32, Quatloos> float_quatloos;
        TUT_CHECK_MSG(float_quatloos == F32Quatloos(0.f), "default float unit is zero");

        LLUnit<F32, Quatloos> float_initialize_quatloos(1);
        TUT_CHECK_MSG(float_initialize_quatloos == F32Quatloos(1.f), "non-zero initialized unit");

        LLUnit<S32, Quatloos> int_quatloos;
        TUT_CHECK_MSG(int_quatloos == S32Quatloos(0), "default int unit is zero");

        int_quatloos = S32Quatloos(42);
        TUT_CHECK_MSG(int_quatloos == S32Quatloos(42), "int assignment is preserved");
        float_quatloos = int_quatloos;
        TUT_CHECK_MSG(float_quatloos == F32Quatloos(42.f), "float assignment from int preserves value");

        int_quatloos = float_quatloos;
        TUT_CHECK_MSG(int_quatloos == S32Quatloos(42), "int assignment from float preserves value");

        float_quatloos = F32Quatloos(42.1f);
        int_quatloos = float_quatloos;
        TUT_CHECK_MSG(int_quatloos == S32Quatloos(42), "int units truncate float units on assignment");

        LLUnit<U32, Quatloos> unsigned_int_quatloos(float_quatloos);
        TUT_CHECK_MSG(unsigned_int_quatloos == S32Quatloos(42), "unsigned int can be initialized from signed int");

        S32Solari int_solari(1);

        float_quatloos = int_solari;
        TUT_CHECK_MSG(float_quatloos == F32Quatloos(0.25f), "fractional units are preserved in conversion from integer to float type");

        int_quatloos = S32Quatloos(1);
        F32Solari float_solari = int_quatloos;
        TUT_CHECK_MSG(float_solari == F32Solari(4.f), "can convert with fractional intermediates from integer to float type");
    }

    TUT_CASE("llunits_test::units_object_t_test_2")
    {
        using namespace tut;
        LLUnit<F32, Quatloos> quatloos(1.f);
        LLUnit<F32, Latinum> latinum_bars(quatloos);
        TUT_CHECK_MSG(latinum_bars == F32Latinum(1.f / 4.f), "conversion between units is automatic via initialization");

        latinum_bars = S32Latinum(256);
        quatloos = latinum_bars;
        TUT_CHECK_MSG(quatloos == S32Quatloos(1024), "conversion between units is automatic via assignment, and bidirectional");

        LLUnit<S32, Quatloos> single_quatloo(1);
        LLUnit<F32, Latinum> quarter_latinum = single_quatloo;
        TUT_CHECK_MSG(quarter_latinum == F32Latinum(0.25f), "division of integer unit preserves fractional values when converted to float unit");
    }

    TUT_CASE("llunits_test::units_object_t_test_3")
    {
        using namespace tut;
        LLUnit<F32, Quatloos> quatloos(1024);
        LLUnit<F32, Solari> solari(quatloos);
        TUT_CHECK_MSG(solari == S32Solari(4096), "conversions can work between indirectly related units: Quatloos -> Latinum -> Solari");

        LLUnit<F32, Latinum> latinum_bars = solari;
        TUT_CHECK_MSG(latinum_bars == S32Latinum(256), "Non base units can be converted between each other");
    }

    TUT_CASE("llunits_test::units_object_t_test_4")
    {
        using namespace tut;
        // exercise math operations
        LLUnit<F32, Quatloos> quatloos(1.f);
        quatloos *= 4.f;
        TUT_ENSURE(quatloos == S32Quatloos(4));
        quatloos = quatloos * 2;
        TUT_ENSURE(quatloos == S32Quatloos(8));
        quatloos = 2.f * quatloos;
        TUT_ENSURE(quatloos == S32Quatloos(16));

        quatloos += F32Quatloos(4.f);
        TUT_ENSURE(quatloos == S32Quatloos(20));
        quatloos += S32Quatloos(4);
        TUT_ENSURE(quatloos == S32Quatloos(24));
        quatloos = quatloos + S32Quatloos(4);
        TUT_ENSURE(quatloos == S32Quatloos(28));
        quatloos = S32Quatloos(4) + quatloos;
        TUT_ENSURE(quatloos == S32Quatloos(32));
        quatloos += quatloos * 3;
        TUT_ENSURE(quatloos == S32Quatloos(128));

        quatloos -= quatloos / 4 * 3;
        TUT_ENSURE(quatloos == S32Quatloos(32));
        quatloos = quatloos - S32Quatloos(8);
        TUT_ENSURE(quatloos == S32Quatloos(24));
        quatloos -= S32Quatloos(4);
        TUT_ENSURE(quatloos == S32Quatloos(20));
        quatloos -= F32Quatloos(4.f);
        TUT_ENSURE(quatloos == S32Quatloos(16));

        quatloos /= 2.f;
        TUT_ENSURE(quatloos == S32Quatloos(8));
        quatloos = quatloos / 4;
        TUT_ENSURE(quatloos == S32Quatloos(2));

        F32 ratio = quatloos / LLUnit<F32, Quatloos>(2.f);
        TUT_ENSURE(ratio == 1);
        ratio = quatloos / LLUnit<F32, Solari>(8.f);
        TUT_ENSURE(ratio == 1);

        quatloos += LLUnit<F32, Solari>(8.f);
        TUT_ENSURE(quatloos == S32Quatloos(4));
        quatloos -= LLUnit<F32, Latinum>(1.f);
        TUT_ENSURE(quatloos == S32Quatloos(0));
    }

    TUT_CASE("llunits_test::units_object_t_test_5")
    {
        using namespace tut;
        LLUnit<S32, Quatloos> quatloos(1);
        TUT_CHECK_MSG(quatloos < S32Quatloos(2), "can perform less than comparison against same type");
        TUT_CHECK_MSG(quatloos < F32Quatloos(2.f), "can perform less than comparison against different storage type");
        TUT_CHECK_MSG(quatloos < S32Latinum(5), "can perform less than comparison against different units");
        TUT_CHECK_MSG(quatloos < F32Latinum(5.f), "can perform less than comparison against different storage type and units");

        TUT_CHECK_MSG(quatloos > S32Quatloos(0), "can perform greater than comparison against same type");
        TUT_CHECK_MSG(quatloos > F32Quatloos(0.f), "can perform greater than comparison against different storage type");
        TUT_CHECK_MSG(quatloos > S32Latinum(0), "can perform greater than comparison against different units");
        TUT_CHECK_MSG(quatloos > F32Latinum(0.f), "can perform greater than comparison against different storage type and units");
    }

    TUT_CASE("llunits_test::units_object_t_test_6")
    {
        using namespace tut;
        S32Quatloos quatloos(1);
        TUT_CHECK_MSG(accept_explicit_quatloos(S32Quatloos(1)), "can pass unit values as argument");
        TUT_CHECK_MSG(accept_explicit_quatloos(quatloos), "can pass unit values as argument");
    }

    TUT_CASE("llunits_test::units_object_t_test_7")
    {
        using namespace tut;
        LLUnit<F32, Quatloos> quatloos;
        LLUnitImplicit<F32, Quatloos> quatloos_implicit = quatloos + S32Quatloos(1);
        TUT_CHECK_MSG(quatloos_implicit == 1, "can initialize implicit unit from explicit");

        quatloos = quatloos_implicit;
        TUT_CHECK_MSG(quatloos == S32Quatloos(1), "can assign implicit unit to explicit unit");
        quatloos += quatloos_implicit;
        TUT_CHECK_MSG(quatloos == S32Quatloos(2), "can perform math operation using mixture of implicit and explicit units");

        // math operations on implicits
        quatloos_implicit = 1;
        TUT_ENSURE(quatloos_implicit == 1);

        quatloos_implicit += 2;
        TUT_ENSURE(quatloos_implicit == 3);

        quatloos_implicit *= 2;
        TUT_ENSURE(quatloos_implicit == 6);

        quatloos_implicit -= 1;
        TUT_ENSURE(quatloos_implicit == 5);

        quatloos_implicit /= 5;
        TUT_ENSURE(quatloos_implicit == 1);

        quatloos_implicit = quatloos_implicit + 3 + quatloos_implicit;
        TUT_ENSURE(quatloos_implicit == 5);

        quatloos_implicit = 10 - quatloos_implicit - 1;
        TUT_ENSURE(quatloos_implicit == 4);

        quatloos_implicit = 2 * quatloos_implicit * 2;
        TUT_ENSURE(quatloos_implicit == 16);

        F32 one_half = quatloos_implicit / (quatloos_implicit * 2);
        TUT_ENSURE(one_half == 0.5f);

        // implicit conversion to POD
        F32 float_val = quatloos_implicit;
        TUT_CHECK_MSG(float_val == 16, "implicit units convert implicitly to regular values");

        S32 int_val = (S32)quatloos_implicit;
        TUT_CHECK_MSG(int_val == 16, "implicit units convert implicitly to regular values");

        // conversion of implicits
        LLUnitImplicit<F32, Latinum> latinum_implicit(2);
        TUT_CHECK_MSG(latinum_implicit * 2 == quatloos_implicit, "implicit units of different types are comparable");

        quatloos_implicit += F32Quatloos(10);
        TUT_CHECK_MSG(quatloos_implicit == 26, "can add-assign explicit units");

        quatloos_implicit -= F32Quatloos(10);
        TUT_CHECK_MSG(quatloos_implicit == 16, "can subtract-assign explicit units");

        // comparisons
        TUT_CHECK_MSG(quatloos_implicit > F32QuatloosImplicit(0.f), "can compare greater than implicit unit");
        TUT_CHECK_MSG(quatloos_implicit > F32Quatloos(0.f), "can compare greater than non-implicit unit");
        TUT_CHECK_MSG(quatloos_implicit >= F32QuatloosImplicit(0.f), "can compare greater than or equal to implicit unit");
        TUT_CHECK_MSG(quatloos_implicit >= F32Quatloos(0.f), "can compare greater than or equal to non-implicit unit");
        TUT_CHECK_MSG(quatloos_implicit < F32QuatloosImplicit(20.f), "can compare less than implicit unit");
        TUT_CHECK_MSG(quatloos_implicit < F32Quatloos(20.f), "can compare less than non-implicit unit");
        TUT_CHECK_MSG(quatloos_implicit <= F32QuatloosImplicit(20.f), "can compare less than or equal to implicit unit");
        TUT_CHECK_MSG(quatloos_implicit <= F32Quatloos(20.f), "can compare less than or equal to non-implicit unit");
    }

    TUT_CASE("llunits_test::units_object_t_test_8")
    {
        using namespace tut;
        U32Bytes max_bytes(U32_MAX);
        S32Megabytes mega_bytes = max_bytes;
        TUT_CHECK_MSG(mega_bytes == (S32Megabytes)4095, "max available precision is used when converting units");

        mega_bytes = (S32Megabytes)-5 + (U32Megabytes)1;
        TUT_CHECK_MSG(mega_bytes == (S32Megabytes)-4, "can mix signed and unsigned in units addition");

        mega_bytes = (U32Megabytes)5 + (S32Megabytes)-1;
        TUT_CHECK_MSG(mega_bytes == (S32Megabytes)4, "can mix unsigned and signed in units addition");
    }

    TUT_CASE("llunits_test::units_object_t_test_9")
    {
        using namespace tut;
        U32Gigabytes GB(1);
        U32Megabytes MB(GB);
        U32Kilobytes KB(GB);
        U32Bytes B(GB);

        TUT_CHECK_MSG(MB.value() == 1024, "GB -> MB conversion");
        TUT_CHECK_MSG(KB.value() == 1024 * 1024, "GB -> KB conversion");
        TUT_CHECK_MSG(B.value() == 1024 * 1024 * 1024, "GB -> B conversion");

        KB = U32Kilobytes(1);
        U32Kilobits Kb(KB);
        U32Bits b(KB);
        TUT_CHECK_MSG(Kb.value() == 8, "KB -> Kb conversion");
        TUT_CHECK_MSG(b.value() == 8 * 1024, "KB -> b conversion");

        U32Days days(1);
        U32Hours hours(days);
        U32Minutes minutes(days);
        U32Seconds seconds(days);
        U32Milliseconds ms(days);

        TUT_CHECK_MSG(hours.value() == 24, "days -> hours conversion");
        TUT_CHECK_MSG(minutes.value() == 24 * 60, "days -> minutes conversion");
        TUT_CHECK_MSG(seconds.value() == 24 * 60 * 60, "days -> seconds conversion");
        TUT_CHECK_MSG(ms.value() == 24 * 60 * 60 * 1000, "days -> ms conversion");

        U32Kilometers km(1);
        U32Meters m(km);
        U32Centimeters cm(km);
        U32Millimeters mm(km);

        TUT_CHECK_MSG(m.value() == 1000, "km -> m conversion");
        TUT_CHECK_MSG(cm.value() == 1000 * 100, "km -> cm conversion");
        TUT_CHECK_MSG(mm.value() == 1000 * 1000, "km -> mm conversion");

        U32Gigahertz GHz(1);
        U32Megahertz MHz(GHz);
        U32Kilohertz KHz(GHz);
        U32Hertz     Hz(GHz);

        TUT_CHECK_MSG(MHz.value() == 1000, "GHz -> MHz conversion");
        TUT_CHECK_MSG(KHz.value() == 1000 * 1000, "GHz -> KHz conversion");
        TUT_CHECK_MSG(Hz.value() == 1000 * 1000 * 1000, "GHz -> Hz conversion");

        F32Radians rad(6.2831853071795f);
        S32Degrees deg(rad);
        TUT_CHECK_MSG(deg.value() == 360, "radians -> degrees conversion");

        F32Percent percent(50);
        F32Ratio ratio(percent);
        TUT_CHECK_MSG(ratio.value() == 0.5f, "percent -> ratio conversion");

        U32Kilotriangles ktris(1);
        U32Triangles tris(ktris);
        TUT_CHECK_MSG(tris.value() == 1000, "kilotriangles -> triangles conversion");
    }

    TUT_CASE("llunits_test::units_object_t_test_10")
    {
        using namespace tut;
        F32Celcius float_celcius(100);
        F32Fahrenheit float_fahrenheit(float_celcius);
        TUT_CHECK_MSG(value_near(float_fahrenheit.value(), 212, 0.1f), "floating point celcius -> fahrenheit conversion using linear transform");

        float_celcius = float_fahrenheit;
        TUT_CHECK_MSG(value_near(float_celcius.value(), 100.f, 0.1f), "floating point fahrenheit -> celcius conversion using linear transform (round trip)");

        S32Celcius int_celcius(100);
        S32Fahrenheit int_fahrenheit(int_celcius);
        TUT_CHECK_MSG(int_fahrenheit.value() == 212, "integer celcius -> fahrenheit conversion using linear transform");

        int_celcius = int_fahrenheit;
        TUT_CHECK_MSG(int_celcius.value() == 100, "integer fahrenheit -> celcius conversion using linear transform (round trip)");
    }
}
