// ---------------------------------------------------------------------------
// Auto-generated from threadsafeschedule_test.cpp at 2025-10-16T20:37:41+00:00
// Generated by gen_tut_to_doctest.py
// ---------------------------------------------------------------------------
#include "doctest.h"
#include "indra/test/ll_doctest_helpers.h"
#include "indra/test/tut_compat_doctest.h"
#include "linden_common.h"
#include "threadsafeschedule.h"
#include <chrono>

// Original helper code skipped (missing includes: complex-fixture)
// /**
//  * @file   threadsafeschedule_test.cpp
//  * @author Nat Goodspeed
//  * @date   2021-10-04
//  * @brief  Test for threadsafeschedule.
//  *
//  * $LicenseInfo:firstyear=2021&license=viewerlgpl$
//  * Copyright (c) 2021, Linden Research, Inc.
//  * $/LicenseInfo$
//  */
//
// // Precompiled header
// // associated header
// // STL headers
// // std headers
// // external library headers
// // other Linden headers
//
// using namespace std::literals::chrono_literals; // ms suffix
// using namespace std::literals::string_literals; // s suffix
// using Queue = LL::ThreadSafeSchedule<std::string>;
//
// /*****************************************************************************
// *   TUT
// *****************************************************************************/
// namespace tut
// {
//     using tut_compat::ensure;
//     using tut_compat::ensure_equals;
//     using tut_compat::ensure_not;
//     using tut_compat::ensure_throws;
//
//         struct threadsafeschedule_data
//         {
//             Queue queue;
//         };
// } // namespace tut // namespace tut

TUT_SUITE("threadsafeschedule")
{
    TUT_CASE("threadsafeschedule_test::push")
    {
        DOCTEST_FAIL("TODO: missing includes: complex-fixture");
        // Original snippet:
        // template<> template<>
        //     void object::test<1>()
        //     {
        //         set_test_name("push");
        //         // Simply calling push() a few times might result in indeterminate
        //         // delivery order if the resolution of steady_clock is coarser than
        //         // the real time required for each push() call. Explicitly increment
        //         // the timestamp for each one -- but since we're passing explicit
        //         // timestamps, make the queue reorder them.
        //         auto now{ Queue::Clock::now() };
        //         queue.push(Queue::TimeTuple(now + 200ms, "ghi"s));
        //         // Given the various push() overloads, you have to match the type
        //         // exactly: conversions are ambiguous.
        //         queue.push(now, "abc"s);
        //         queue.push(now + 100ms, "def"s);
        //         queue.close();
        //         auto entry = queue.pop();
        //         ensure_equals("failed to pop first", std::get<0>(entry), "abc"s);
        //         entry = queue.pop();
        //         ensure_equals("failed to pop second", std::get<0>(entry), "def"s);
        //         ensure("queue not closed", queue.isClosed());
        //         ensure("queue prematurely done", ! queue.done());
        //         std::string s;
        //         bool popped = queue.tryPopFor(1s, s);
        //         ensure("failed to pop third", popped);
        //         ensure_equals("third is wrong", s, "ghi"s);
        //         popped = queue.tryPop(s);
        //         ensure("queue not empty", ! popped);
        //         ensure("queue not done", queue.done());
        //     }
    }
}
