// ---------------------------------------------------------------------------
// Auto-generated from tuple_test.cpp at 2025-10-16T20:37:41+00:00
// Generated by gen_tut_to_doctest.py
// ---------------------------------------------------------------------------
#include "doctest.h"
#include "indra/test/ll_doctest_helpers.h"
#include "indra/test/tut_compat_doctest.h"
#include "linden_common.h"
#include "tuple.h"

/**
 * @file   tuple_test.cpp
 * @author Nat Goodspeed
 * @date   2021-10-04
 * @brief  Test for tuple.
 *
 * $LicenseInfo:firstyear=2021&license=viewerlgpl$
 * Copyright (c) 2021, Linden Research, Inc.
 * $/LicenseInfo$
 */

// Precompiled header
// associated header
// STL headers
// std headers
// external library headers
// other Linden headers

/*****************************************************************************
*   TUT
*****************************************************************************/
namespace tut
{
    using tut_compat::ensure;
    using tut_compat::ensure_equals;
    using tut_compat::ensure_not;
    using tut_compat::ensure_throws;

        struct tuple_data
        {
        };
} // namespace tut // namespace tut

TUT_SUITE("tuple")
{
    TUT_CASE("tuple_test::tuple")
    {
        using namespace tut;
        TUT_SET_TEST_NAME("tuple");
        std::tuple<std::string, int> tup{ "abc", 17 };
        std::tuple<int, std::string, int> ptup{ tuple_cons(34, tup) };
        std::tuple<std::string, int> tup2;
        int i;
        std::tie(i, tup2) = tuple_split(ptup);
        TUT_ENSURE_EQ("tuple_car() fail", i, 34);
        TUT_ENSURE_EQ("tuple_cdr() (0) fail", std::get<0>(tup2), "abc");
        TUT_ENSURE_EQ("tuple_cdr() (1) fail", std::get<1>(tup2), 17);
    }
}
