// ---------------------------------------------------------------------------
// Auto-generated from alignment_test.cpp at 2025-10-17T12:56:17+00:00
// Generated by gen_tut_to_doctest.py
// ---------------------------------------------------------------------------
#include "doctest.h"
#include "indra/test/ll_doctest_helpers.h"
#include "indra/test/tut_compat_doctest.h"
#include "linden_common.h"
#include "../llmath.h"
#include "../llsimdmath.h"
#include "../llvector4a.h"

/**
 * @file v3dmath_test.cpp
 * @author Vir
 * @date 2011-12
 * @brief v3dmath test cases.
 *
 * $LicenseInfo:firstyear=2011&license=viewerlgpl$
 * Second Life Viewer Source Code
 * Copyright (C) 2011, Linden Research, Inc.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation;
 * version 2.1 of the License only.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 * Linden Research, Inc., 945 Battery Street, San Francisco, CA  94111  USA
 * $/LicenseInfo$
 */

// Tests related to allocating objects with alignment constraints, particularly for SSE support.


namespace tut
{
    using tut_compat::ensure;
    using tut_compat::ensure_equals;
    using tut_compat::ensure_not;
    using tut_compat::ensure_throws;

    #define is_aligned(ptr,alignment) ((reinterpret_cast<uintptr_t>(ptr))%(alignment)==0)
    #define is_aligned_relative(ptr,base_ptr,alignment) ((reinterpret_cast<uintptr_t>(ptr)-reinterpret_cast<uintptr_t>(base_ptr))%(alignment)==0)

    struct alignment_test {};


    LL_ALIGN_PREFIX(16)
    class MyVector4a
    {
    public:
        void* operator new(size_t size)
        {
            return ll_aligned_malloc_16(size);
        }

        void operator delete(void *p)
        {
            ll_aligned_free_16(p);
        }

        void* operator new[](size_t count)
        {   // try to allocate count bytes for an array
            return ll_aligned_malloc_16(count);
        }

        void operator delete[](void *p)
        {
            ll_aligned_free_16(p);
        }

        LLQuad mQ;
    } LL_ALIGN_POSTFIX(16);


    // Verify that aligned allocators perform as advertised.


    // In-place allocation of objects and arrays.


    // Heap allocation of objects and arrays.
} // namespace tut

TUT_SUITE("alignment_test")
{
    TUT_CASE("alignment_test::alignment_test_object_t_test_1")
    {
        using namespace tut;
        #   ifdef LL_DEBUG
        //  skip("This test fails on Windows when compiled in debug mode.");
        #   endif

            const int num_tests = 7;
            void *align_ptr;
            for (int i=0; i<num_tests; i++)
            {
                align_ptr = ll_aligned_malloc_16(sizeof(MyVector4a));
                TUT_CHECK_MSG(is_aligned(align_ptr,16), "ll_aligned_malloc_16 failed");

                align_ptr = ll_aligned_realloc_16(align_ptr,2*sizeof(MyVector4a), sizeof(MyVector4a));
                TUT_CHECK_MSG(is_aligned(align_ptr,16), "ll_aligned_realloc_16 failed");

                ll_aligned_free_16(align_ptr);

                align_ptr = ll_aligned_malloc_32(sizeof(MyVector4a));
                TUT_CHECK_MSG(is_aligned(align_ptr,32), "ll_aligned_malloc_32 failed");
                ll_aligned_free_32(align_ptr);
            }
    }

    TUT_CASE("alignment_test::alignment_test_object_t_test_2")
    {
        using namespace tut;
        MyVector4a vec1;
        TUT_CHECK_MSG(is_aligned(&vec1,16), "LLAlignment vec1 unaligned");

        MyVector4a veca[12];
        TUT_CHECK_MSG(is_aligned(veca,16), "LLAlignment veca unaligned");
    }

    TUT_CASE("alignment_test::alignment_test_object_t_test_3")
    {
        using namespace tut;
        #   ifdef LL_DEBUG
        //  skip("This test fails on Windows when compiled in debug mode.");
        #   endif

            const int ARR_SIZE = 7;
            for(int i=0; i<ARR_SIZE; i++)
            {
                MyVector4a *vecp = new MyVector4a;
                TUT_CHECK_MSG(is_aligned(vecp,16), "LLAlignment vecp unaligned");
                delete vecp;
            }

            MyVector4a *veca = new MyVector4a[ARR_SIZE];
            //std::cout << "veca base is " << (S32) veca << std::endl;
            TUT_CHECK_MSG(is_aligned(veca,16), "LLAligment veca base");
            for(int i=0; i<ARR_SIZE; i++)
            {
                std::cout << "veca[" << i << "]" << std::endl;
                TUT_CHECK_MSG(is_aligned(&veca[i],16), "LLAlignment veca member unaligned");
            }
            delete [] veca;
    }
}
