// ---------------------------------------------------------------------------
// Auto-generated from xform_test.cpp at 2025-10-17T12:56:18+00:00
// Generated by gen_tut_to_doctest.py
// ---------------------------------------------------------------------------
#include "doctest.h"
#include "indra/test/ll_doctest_helpers.h"
#include "indra/test/tut_compat_doctest.h"
#include "linden_common.h"
#include "../xform.h"

/**
 * @file xform_test.cpp
 * @author Adroit
 * @date March 2007
 * @brief Test cases for LLXform
 *
 * $LicenseInfo:firstyear=2007&license=viewerlgpl$
 * Second Life Viewer Source Code
 * Copyright (C) 2010, Linden Research, Inc.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation;
 * version 2.1 of the License only.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 * Linden Research, Inc., 945 Battery Street, San Francisco, CA  94111  USA
 * $/LicenseInfo$
 */



namespace tut
{
    using tut_compat::ensure;
    using tut_compat::ensure_equals;
    using tut_compat::ensure_not;
    using tut_compat::ensure_throws;

        struct xform_test
        {
        };

        //test case for init(), getParent(), getRotation(), getPositionW(), getWorldRotation() fns.


        // test cases for
        // setScale(const LLVector3& scale)
        // setScale(const F32 x, const F32 y, const F32 z)
        // setRotation(const F32 x, const F32 y, const F32 z)
        // setPosition(const F32 x, const F32 y, const F32 z)
        // getLocalMat4(LLMatrix4 &mat)


        // test cases for inline bool setParent(LLXform *parent) and getParent() fn.




        //to test init() and getWorldMatrix() fns.


        //to test mMin.clearVec() and mMax.clearVec() fns


        //test case of update() fn.
} // namespace tut

TUT_SUITE("xform_test")
{
    TUT_CASE("xform_test::xform_test_object_t_test_1")
    {
        using namespace tut;
        LLXform xform_obj;
        LLVector3 emptyVec(0.f,0.f,0.f);
        LLVector3 initialScaleVec(1.f,1.f,1.f);

        TUT_CHECK_MSG(!xform_obj.getParent() && !xform_obj.isChanged() &&
            xform_obj.getPosition() == emptyVec &&
            (xform_obj.getRotation()).isIdentity() &&
            xform_obj.getScale() == initialScaleVec &&
            xform_obj.getPositionW() == emptyVec &&
            (xform_obj.getWorldRotation()).isIdentity() &&
            !xform_obj.getScaleChildOffset(), "LLXform empty constructor failed: ");
    }

    TUT_CASE("xform_test::xform_test_object_t_test_2")
    {
        using namespace tut;
        LLMatrix4 llmat4;
        LLXform xform_obj;

        F32 x = 3.6f;
        F32 y = 5.5f;
        F32 z = 4.2f;
        F32 w = 0.f;
        F32 posz = z + 2.122f;
        LLVector3 vec(x, y, z);
        xform_obj.setScale(x, y, z);
        xform_obj.setPosition(x, y, posz);
        TUT_CHECK_MSG(xform_obj.getScale() == vec, "setScale failed: ");

        vec.setVec(x, y, posz);
        TUT_CHECK_MSG(xform_obj.getPosition() == vec, "getPosition failed: ");

        x = x * 2.f;
        y = y + 2.3f;
        z = posz * 4.f;
        vec.setVec(x, y, z);
        xform_obj.setPositionX(x);
        xform_obj.setPositionY(y);
        xform_obj.setPositionZ(z);
        TUT_CHECK_MSG(xform_obj.getPosition() == vec, "setPositionX/Y/Z failed: ");

        xform_obj.setScaleChildOffset(true);
        TUT_CHECK_MSG(xform_obj.getScaleChildOffset(), "setScaleChildOffset failed: ");

        vec.setVec(x, y, z);

        xform_obj.addPosition(vec);
        vec += vec;
        TUT_CHECK_MSG(xform_obj.getPosition() == vec, "addPosition failed: ");

        xform_obj.setScale(vec);
        TUT_CHECK_MSG(xform_obj.getScale() == vec, "setScale vector failed: ");

        LLQuaternion quat(x, y, z, w);
        xform_obj.setRotation(quat);
        TUT_CHECK_MSG(xform_obj.getRotation() == quat, "setRotation quat failed: ");

        xform_obj.setRotation(x, y, z, w);
        TUT_CHECK_MSG(xform_obj.getRotation() == quat, "getRotation 2 failed: ");

        xform_obj.setRotation(x, y, z);
        quat.setQuat(x,y,z);
        TUT_CHECK_MSG(xform_obj.getRotation() == quat, "setRotation xyz failed: ");

        // LLXform::setRotation(const F32 x, const F32 y, const F32 z)
        //      Does normalization
        // LLXform::setRotation(const F32 x, const F32 y, const F32 z, const F32 s)
        //      Simply copies the individual values - does not do any normalization.
        // Is that the expected behavior?
    }

    TUT_CASE("xform_test::xform_test_object_t_test_3")
    {
        using namespace tut;
        LLXform xform_obj;
        LLXform par;
        LLXform grandpar;
        xform_obj.setParent(&par);
        par.setParent(&grandpar);
        TUT_CHECK_MSG(&par == xform_obj.getParent(), "setParent/getParent failed: ");
        TUT_CHECK_MSG(&grandpar == xform_obj.getRoot(), "getRoot failed: ");
        TUT_CHECK_MSG(grandpar.isRoot() && !par.isRoot() && !xform_obj.isRoot(), "isRoot failed: ");
        TUT_CHECK_MSG(grandpar.isRootEdit() && !par.isRootEdit() && !xform_obj.isRootEdit(), "isRootEdit failed: ");
    }

    TUT_CASE("xform_test::xform_test_object_t_test_4")
    {
        using namespace tut;
        LLXform xform_obj;
        xform_obj.setChanged(LLXform::TRANSLATED | LLXform::ROTATED | LLXform::SCALED);
        TUT_CHECK_MSG(xform_obj.isChanged(), "setChanged/isChanged failed: ");

        xform_obj.clearChanged(LLXform::TRANSLATED | LLXform::ROTATED | LLXform::SCALED);
        TUT_CHECK_MSG(!xform_obj.isChanged(), "clearChanged failed: ");

        LLVector3 llvect3(12.4f, -5.6f, 0.34f);
        xform_obj.setScale(llvect3);
        TUT_CHECK_MSG(xform_obj.isChanged(LLXform::SCALED), "setScale did not set SCALED flag: ");
        xform_obj.setPosition(1.2f, 2.3f, 3.4f);
        TUT_CHECK_MSG(xform_obj.isChanged(LLXform::TRANSLATED), "setScale did not set TRANSLATED flag: ");
        TUT_CHECK_MSG(xform_obj.isChanged(LLXform::TRANSLATED | LLXform::SCALED), "TRANSLATED reset SCALED flag: ");
        xform_obj.clearChanged(LLXform::SCALED);
        TUT_CHECK_MSG(!xform_obj.isChanged(LLXform::SCALED), "reset SCALED failed: ");
        xform_obj.setRotation(1, 2, 3, 4);
        TUT_CHECK_MSG(xform_obj.isChanged(LLXform::TRANSLATED | LLXform::ROTATED), "ROTATION flag not set ");
        xform_obj.setScale(llvect3);
        TUT_CHECK_MSG(xform_obj.isChanged(LLXform::MOVED), "ROTATION flag not set ");
    }

    TUT_CASE("xform_test::xform_test_object_t_test_5")
    {
        using namespace tut;
        LLXformMatrix formMatrix_obj;
        formMatrix_obj.init();
        LLMatrix4 mat4_obj;

        TUT_CHECK_MSG(1.f == formMatrix_obj.getWorldMatrix().mMatrix[0][0], "1. The value is not NULL");
        TUT_CHECK_MSG(0.f == formMatrix_obj.getWorldMatrix().mMatrix[0][1], "2. The value is not NULL");
        TUT_CHECK_MSG(0.f == formMatrix_obj.getWorldMatrix().mMatrix[0][2], "3. The value is not NULL");
        TUT_CHECK_MSG(0.f == formMatrix_obj.getWorldMatrix().mMatrix[0][3], "4. The value is not NULL");
        TUT_CHECK_MSG(0.f == formMatrix_obj.getWorldMatrix().mMatrix[1][0], "5. The value is not NULL");
        TUT_CHECK_MSG(1.f == formMatrix_obj.getWorldMatrix().mMatrix[1][1], "6. The value is not NULL");
        TUT_CHECK_MSG(0.f == formMatrix_obj.getWorldMatrix().mMatrix[1][2], "7. The value is not NULL");
        TUT_CHECK_MSG(0.f == formMatrix_obj.getWorldMatrix().mMatrix[1][3], "8. The value is not NULL");
        TUT_CHECK_MSG(0.f == formMatrix_obj.getWorldMatrix().mMatrix[2][0], "9. The value is not NULL");
        TUT_CHECK_MSG(0.f == formMatrix_obj.getWorldMatrix().mMatrix[2][1], "10. The value is not NULL");
        TUT_CHECK_MSG(1.f == formMatrix_obj.getWorldMatrix().mMatrix[2][2], "11. The value is not NULL");
        TUT_CHECK_MSG(0.f == formMatrix_obj.getWorldMatrix().mMatrix[2][3], "12. The value is not NULL");
        TUT_CHECK_MSG(0.f == formMatrix_obj.getWorldMatrix().mMatrix[3][0], "13. The value is not NULL");
        TUT_CHECK_MSG(0.f == formMatrix_obj.getWorldMatrix().mMatrix[3][1], "14. The value is not NULL");
        TUT_CHECK_MSG(0.f == formMatrix_obj.getWorldMatrix().mMatrix[3][2], "15. The value is not NULL");
        TUT_CHECK_MSG(1.f == formMatrix_obj.getWorldMatrix().mMatrix[3][3], "16. The value is not NULL");
    }

    TUT_CASE("xform_test::xform_test_object_t_test_6")
    {
        using namespace tut;
        LLXformMatrix formMatrix_obj;
        formMatrix_obj.init();
        LLVector3 llmin_vec3;
        LLVector3 llmax_vec3;
        formMatrix_obj.getMinMax(llmin_vec3, llmax_vec3);
        TUT_CHECK_MSG(0.f == llmin_vec3.mV[0], "1. The value is not NULL");
        TUT_CHECK_MSG(0.f == llmin_vec3.mV[1], "2. The value is not NULL");
        TUT_CHECK_MSG(0.f == llmin_vec3.mV[2], "3. The value is not NULL");
        TUT_CHECK_MSG(0.f == llmin_vec3.mV[0], "4. The value is not NULL");
        TUT_CHECK_MSG(0.f == llmin_vec3.mV[1], "5. The value is not NULL");
        TUT_CHECK_MSG(0.f == llmin_vec3.mV[2], "6. The value is not NULL");
    }

    TUT_CASE("xform_test::xform_test_object_t_test_7")
    {
        using namespace tut;
        LLXformMatrix formMatrix_obj;

        LLXformMatrix parent;
        LLVector3 llvecpos(1.0, 2.0, 3.0);
        LLVector3 llvecpospar(10.0, 20.0, 30.0);
        formMatrix_obj.setPosition(llvecpos);
        parent.setPosition(llvecpospar);

        LLVector3 llvecparentscale(1.0, 2.0, 0);
        parent.setScaleChildOffset(true);
        parent.setScale(llvecparentscale);

        LLQuaternion quat(1, 2, 3, 4);
        LLQuaternion quatparent(5, 6, 7, 8);
        formMatrix_obj.setRotation(quat);
        parent.setRotation(quatparent);
        formMatrix_obj.setParent(&parent);

        parent.update();
        formMatrix_obj.update();

        LLVector3 worldPos = llvecpos;
        worldPos.scaleVec(llvecparentscale);
        worldPos *= quatparent;
        worldPos += llvecpospar;

        LLQuaternion worldRot = quat * quatparent;

        TUT_CHECK_MSG(formMatrix_obj.getWorldPosition() == worldPos, "getWorldPosition failed: ");
        TUT_CHECK_MSG(formMatrix_obj.getWorldRotation() == worldRot, "getWorldRotation failed: ");

        TUT_CHECK_MSG(parent.getWorldPosition() == llvecpospar, "getWorldPosition for parent failed: ");
        TUT_CHECK_MSG(parent.getWorldRotation() == quatparent, "getWorldRotation for parent failed: ");
    }
}
